#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2019. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# scrollspeed :
# Set the scroll wheel speed on a mouse using the System Preferences contol panel.

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#
# 05/01/2018 :
#  • This one not working on Sierra. debug need !

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 05/01/2018 :
#  • Modify function presentation.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
#######################
## COMMAND VARIABLES ##
#######################
local VERSION FCT_NAME

VERSION="0.0.1"
FCT_NAME="$(echo $0)"

#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
  cat<<__EOF__
  ${RED}
    usage: 

    Examples:


  ${NC}
__EOF__
}

#-------------------------------------------------------------------------------------------#
#                                              SCRIPT
#-------------------------------------------------------------------------------------------#
banner
if [[ $# == 0 ]];then
 echo "${RED}"
 print "scrollspeed changes the mouse scroll wheel speed via System Preferences"
 print "Usage:  scrollspeed N  [where N ranges from 0 (slowest) to 7 (fastest)]"
 print -n "Open the Keyboard and Mouse Preference Pane? [y/N] "
 echo "${NC}"
        StopIt=""
        read -t 5 -A StopIt

        if [[ $StopIt[1] == (y|Y) ]]; then
            open /System/Library/PreferencePanes/Keyboard.prefPane
            StopIt=""
            return 0
        elif [[ $StopIt = (0|1|2|3|4|5|6|7|8|9|10) ]]; then
            1=$StopIt ; StopIt=""
        else
            return 1
        fi
fi

# Find out if we are running a laptop (to take into account the presence
# of a trackpad control pane which changes the tab number).

machine_type=$(system_profiler -detailLevel -2 | grep Machine | awk '{print $3}' | /usr/bin/head -n 1 )

if [[ $machine_type == *Book ]]; then 
tab_number=3
print "Assuming laptop with a trackpad is being used."
else
tab_number=2
print "Assuming desktop without a laptop trackpad is being used."
fi

# DEBUG:
# print "$machine_type implies tab number $tab_number"

if [[ $1 != (0|1|2|3|4|5|6|7|8|9|10) ]]; then
	 print "Usage:  scrollspeed N  [where N ranges from 0 (slowest) to 7 (fastest)]"
	 print "N must be an integer between 0 and 7"
else
	print "Please wait ...."
	osascript <<-eof
	tell application "Finder"
		activate
		activate application "System Preferences"
		tell application "System Events"
			if (system attribute "sysv") is greater than or equal to 4144 then -- Mac OS X 10.3.0  
				if UI elements enabled then
					tell application process "System Preferences"
						-- note there is no space after the "&" and Mouse is on a new line 
						click button "Keyboard &
						Mouse" of scroll area 1 of window "System Preferences"
						delay 3
						click radio button $tab_number of tab group 1 of window "Keyboard & Mouse"
						set value of slider 3 of tab group 1 of window "Keyboard & Mouse" to $1
					end tell
				else
					beep
					display dialog "GUI Scripting is not enabled" & return & return & "Open System Preferences and check \"Enable access for assistive devices\" in the Universal Access preference pane, then run this script again." with icon stop
					if button returned of result is "OK" then
						tell application "System Preferences"
							activate
							set current pane to pane "com.apple.preference.universalaccess"
						end tell
					end if
				end if
			else
				beep
				display dialog "This computer can't run this script" & return & return & "The script uses Apple's GUI Scripting technology, which requires an upgrade to Mac OS X 10.3 \"Panther\" or newer." with icon caution buttons {"Quit"} default button "Quit"
			end if
		end tell
		tell application "System Preferences"
			quit
		end tell
	end tell
	eof
	if (($1 > 7)); then
	    print "Mouse scroll wheel speed is now set to 7 (the highest value)"
	else 
	    print "Mouse scroll wheel speed is now set to $1"
	fi
fi
