#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2020. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# termWindow  :
# Put in fullscreen, maximize, vertically and horizontally split iterm window.

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 31/07/2020 :
#  • Create this one .

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
#######################
## COMMAND VARIABLES ##
#######################
local VERSION FCT_NAME

VERSION="0.0.1"
FCT_NAME="$(echo $0)"


#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
  echo "${RED}"
  cat<<__EOF__
    usage: $0 [ fullscreen | maximize | hsplit | vsplit | help ]
__EOF__
echo ${NC}
}

# Put iTerm in fullscreen mode
termFullScreen() {

osascript 2>/dev/null <<EOF
       tell application "System Events"
         tell process "iTerm" to keystroke return using command down
end tell

EOF
}

# Maximize iterm window
termMaximize() {
osascript 2>/dev/null <<EOF
tell application "System Events"
          tell process "iTerm" to key code 81 using {option down, command down}
end tell
EOF
}

# Vertically split iterm.
termVSplit() {
osascript 2>/dev/null <<EOF
       tell application "System Events"
         tell process "iTerm" to keystroke "d" using {command down}
end tell

EOF
}

# Horizontally split iterm.
termSplit() {
osascript 2>/dev/null <<EOF
       tell application "System Events"
         tell process "iTerm" to keystroke "d" using {shift down, command down}
end tell

EOF
}

#----------------------------------------------------------------------------------------#
#                                       SCRIPT
#----------------------------------------------------------------------------------------#
emulate -L zsh
banner

case $1 in
	fullscreen)
		termFullScreen
		return 0
		;;
	maximize)
		termMaximize
		return 0
		;;
	hsplit)
		termSplit
		return 0
		;;
	vsplit)
		termVSplit
		return 0
		;;
	help)
		help
		return 0
		;;
	*)
		help
		return 1
		;;
esac


### Modeline {{{
### vim:ft=zsh:foldmethod=marker
### vim:set ts=4:
### }}}



