.\" Manpage for 32bitSafePerl.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH 32bitSafePerl 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
32bitSafePerl \- A wrapper for Perl scripts which will force them to be run by the 32-bit Perl binary since MacPerl is not 64-bit compatible.
.SH SYNOPSIS
32bitSafePerl
.SH DESCRIPTION
32bitSafePerl \- A wrapper for Perl scripts which will force them to be run by the 32-bit Perl binary since MacPerl is not 64-bit compatible. It's intelligent enough to find the appropriate version depending on the version of Mac OS X, regardless of whether "Prefer-32-Bit" has been set, up until Mac OS X 10.7 Lion which no longer has a 32-bit Perl binary.
.SH OPTIONS
The 32bitSafePerl does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
