.\" Manpage for _7z.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _7z 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
_7z \- zsh completions for the 7z command line application. A file archiver with highest compression ratio.
.SH SYNOPSIS
_7z
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
