.\" Manpage for _a2preview.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _a2preview 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_a2preview \- Completion for a2preview; a wrapper for a2ps that makes an ascii text file into a pretty pdf
.SH SYNOPSIS
_a2preview
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
