.\" Manpage for _aireplay-ng.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _aireplay-ng 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
_aireplay-ng \- zsh completions for 'aireplay-ng'
.SH SYNOPSIS
_aireplay-ng
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
