.\" Manpage for _airbase-ng.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _airbase-ng 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
_airbase-ng \- zsh completions for 'airbase-ng'
.SH SYNOPSIS
_airbase-ng
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
