.\" Manpage for _bluetooth.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _bluetooth 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_bluetooth \- Completion for bluetooth. Get status, enable, disable bluetooth.
.SH SYNOPSIS
_bluetooth
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
