.\" Manpage for _cask.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _cask 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_cask \- Completion script for cask
.SH SYNOPSIS
_cask
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
