.\" Manpage for _chflags.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _chflags 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
_chflags \- Completion for command chflags; change file flags.
.SH SYNOPSIS
_chflags
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
