.\" Manpage for _class-dump.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _class-dump 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_class-dump \- Completion for class-dump developer command.
.SH SYNOPSIS
_class-dump
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
