.\" Manpage for _darwinup.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _darwinup 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_darwinup \- Completion for darwinup Install, uninstall, and manage roots
.SH SYNOPSIS
_darwinup
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
