.\" Manpage for _disk.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _disk 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_disk \- Completion for disk wrapper diskutil script to do essantial disk task on darwin.
.SH SYNOPSIS
_disk
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
