.\" Manpage for _docker-compose.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _docker-compose 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
_docker-compose \- Completion script for Docker Compose. Define and run multi-container applications with Docker
.SH SYNOPSIS
_docker-compose
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
