.\" Manpage for _docker-machine.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _docker-machine 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
_docker-machine \- zsh completion for docker-machine. Create and manage machines running Docker.
.SH SYNOPSIS
_docker-machine
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
