.\" Manpage for _fdupes.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _fdupes 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
_fdupes \- Completion for command fdupes; finds duplicate files in a given set of directories.
.SH SYNOPSIS
_fdupes
.SH SEE ALSO
.BR fdupes(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
