.\" Manpage for _gatekeeper.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _gatekeeper 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_gatekeeper \- Completion for gatekeeper which is wrapper script to control gatekeeper on darwin.
.SH SYNOPSIS
_gatekeeper
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
