.\" Manpage for _iprofiler.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _iprofiler 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_iprofiler \- Completion for iprofiler; Measure an application's performance without launching Instruments.app and then visualize the measurements at a later time in Instruments.app
.SH SYNOPSIS
_iprofiler
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
