.\" Manpage for _LaunchLondoncalling.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _LaunchLondoncalling 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_LaunchLondoncalling \- Completion to give options for LaunchLondoncalling. Disable/enable launch MacOS services.
.SH SYNOPSIS
_LaunchLondoncalling
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
