.\" Manpage for _loginitem.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _loginitem 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_loginitem \- Completion for loginitem; manage login items from the command line.
.SH SYNOPSIS
_loginitem
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
