.\" Manpage for _logger.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _logger 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_logger \- Completion script for logger (from bsdutils). System to control logging of events.
.SH SYNOPSIS
_logger
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
