.\" Manpage for _lwp-mirror.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _lwp-mirror 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_lwp-mirror \- Completion for lwp-mirror. Simple mirror utility.
.SH SYNOPSIS
_lwp-mirror
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
