.\" Manpage for _lwp-dump.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _lwp-dump 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_lwp-dump \- Completion for lwp-dump. See what headers and content is returned for a URL.
.SH SYNOPSIS
_lwp-dump
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
