.\" Manpage for _mdfind_pashua.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _mdfind_pashua 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
_mdfind_pashua \- A completion function for mdfind that utilizes Pashua.
.SH DESCRIPTION
 _mdfind_pashua \- A completion function for mdfind that utilizes Pashua.Metadata attributes can be selected from a popup window.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
