.\" Manpage for _port.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _port 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_port \- Completion script for MacPorts
.SH SYNOPSIS
_port
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
