.\" Manpage for _srm.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _srm 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_srm \- Completion script for srm.
.SH SYNOPSIS
_srm
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
