.\" Manpage for _tmpj.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _tmpj 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_tmpj \- Completion for TextMate
.SH SYNOPSIS
_tmpj
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
