.\" Manpage for _tmutil.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _tmutil 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_tmutil \- zsh completion for OSX's tmutil
.SH SYNOPSIS
_tmutil
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
