.\" Manpage for _volatility.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _volatility 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_volatility \- zsh completion for _volatility; a memory forensics analysis platform.
.SH SYNOPSIS
_volatility
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
