.\" Manpage for _wifi.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _wifi 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_wifi \- wifi completion to handle wifi settings and give wifi informations
.SH DESCRIPTION
_wifi \- wifi completion to handle wifi settings and give wifi informations
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
