.\" Manpage for _X11.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _X11 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_X11 \- Completion for X11; Command for X11 or Xorg or Xquartz Desktop.
.SH SYNOPSIS
_X11
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
