.\" Manpage for _xcodebuild.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _xcodebuild 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
_xcodebuild \- Completion for xcodebuild
.SH SYNOPSIS
_xcodebuild
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
