.\" Manpage for acl.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH acl 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
acl \- An acl nuclear option to give access to user $1 to the directory tree rooted at $2
.SH SYNOPSIS
acl [$USERNAME] </Users/$USERNAME/Pictures/iPhoto\\\ Library>
.SH DESCRIPTION
acl \- Give a single username followed by a single directory. Give a single username followed by a single directory
.SH OPTIONS

.IP acl [$USERNAME] <SINGLEDIRECTORY>
.B Give a single username followed by a single directory

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
