.\" Manpage for apache.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH apache 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
apache \- Apache HTTP Server utility script.
.SH SYNOPSIS
apache
.SH DESCRIPTION
apache \- Apache HTTP Server utility script.
.SH OPTIONS
The apache does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR apachectl(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
