.\" Manpage for archivedir.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH archivedir 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
archivedir \- Create a compressed archive of the specified directory
.SH SYNOPSIS
archivedir <directory>
.SH DESCRIPTION
archivedir \- Create a compressed archive of the specified directory
.SH OPTIONS
The archivedir does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
