.\" Manpage for archall.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH archall 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
archall \- Archive all files that one directory contains.
.SH SYNOPSIS
archall
.SH DESCRIPTION
archall \- Archive all files that one directory contains.
.SH OPTIONS
The archall does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
