.\" Manpage for breww.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH breww 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
breww \- Homebrew utility.
.SH SYNOPSIS
breww
.SH DESCRIPTION
breww \- Homebrew utility.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
