.\" Manpage for cd_.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH cd_ 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
cd_ \- Get the numbered string position in the last line and cd to it (or it's directory)
.SH SYNOPSIS
cd_ <argument_number>
.SH DESCRIPTION
cd_ \- eg: ls one two three four five six

 cd_ 4  is the same as cd four
 cd_ -2 is the same as cd five

.SH OPTIONS
The cd_ does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
