.\" Manpage for CDataType.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH CDataType 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
CDataType \- Enumerate C data type and values.
.SH SYNOPSIS
CDataType
.SH DESCRIPTION
CDataType \- Enumerate C data type and values.
.SH OPTIONS
The CDataType does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
