.\" Manpage for change-extension.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH change-extension 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
change-extension \- Change file extensions recursively in current directory
.SH SYNOPSIS
change-extension <DIRECTORY> <EXTENSION>
.SH DESCRIPTION
change-extension \- Change file extensions recursively in current directory
.SH OPTIONS
The change-extension does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
