.\" Manpage for compildis.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH compildis 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
compildis \- Disable C compilation program for security.
.SH SYNOPSIS
compildis
.SH DESCRIPTION
compildis \- Disable C compilation program for security.
.SH OPTIONS
The compildis does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR compilena(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
