.\" Manpage for cpu_infos.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH cpu_infos 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
cpu_infos \- Give CPU name and characteristics.
.SH SYNOPSIS
cpu_infos
.SH DESCRIPTION
cpu_infos \- Give CPU name and characteristics.
.SH OPTIONS
The cpu_infos does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR sysctl(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
