.\" Manpage for curlito.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH curlito 7 "06 Feb 2020" "1.0" "curlito man page"
.SH NAME
curlito \- Download file by extentions
.SH SYNOPSIS
curlito Query index of / + [foldername] + [filetype]
.SH DESCRIPTION
curlito \- Query index of and download file by extensions 
.SH OPTIONS

.IP "curlito [help]".
.B Obtain program help info.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
