.\" Manpage for cuttail.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH cuttail 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
cuttail \- Cut last n lines in file, 10 by default
.SH SYNOPSIS
cuttail <file>
.SH DESCRIPTION
cuttail \- Cut last n lines in file, 10 by default
.SH OPTIONS
The cuttail does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR sed(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
