.\" Manpage for dashboard.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH dasboard 7 "06 Feb 2020" "MacOS"  "MacOS Darwin ZaemonSH customization"
.SH NAME
dashboard \- Manipulate dashboard from CLI.
.SH SYNOPSIS
dashboard [
.B status | enable | disable
] 
.SH DESCRIPTION
dashboard: Wrapper script to control dashboard on darwin
.SH OPTIONS

.IP "dashboard [status]"
.B Get the dashboard status.

.IP "dashboard [enable]"
.B Activate the dashboard.

.IP "dashboard [disable]"
.B Deactivate the dashboard.

.IP "dashboard [help]"
.B Obtain program help info.

.SH BUGS
No known bugs.
.SH AUTHOR
your Name (zucchelli.bryan@gmail.com)
