.\" Manpage for decToHex.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH decToHex 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
decToHex \- Convert decimal to hexadecimal
.SH SYNOPSIS
decToHex <DECIMAL_NUMBER>
.SH DESCRIPTION
decToHex \- Convert decimal to hexadecimal
.SH OPTIONS
The decToHex does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR decToBin(7)
.BR bc(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
