.\" Manpage for dhcp.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH dhcp 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
dhcp \-  Function to renew a dynamically allocated IP address via BOOTP or DHCP.
.SH SYNOPSIS
dhcp
.SH DESCRIPTION
dhcp \-  Function to renew a dynamically allocated IP address via BOOTP or DHCP. Try en0 first, and then try en1r, Finally, test the IP address.
.SH OPTIONS
The dhcp does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
