.\" Manpage for diskhogs.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH diskhogs 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
diskhogs \- Disk quota analysis tool for Unix.
.SH SYNOPSIS
diskhogs
.SH DESCRIPTION
diskhogs \- Disk quota analysis tool for Unix, assumes all user accounts are >= UID 100. Emails message to each violating user and reports a summary to the screen
.SH OPTIONS
The diskhogs does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
