.\" Manpage for display.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH display 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
display \- Show display information.
.SH SYNOPSIS
display [ status | resolution | help ]
.SH DESCRIPTION
display \- Show display information.
.SH OPTIONS

.IP "display [status]"
.B Display status.

.IP "display [resolution]"
.B A small command line script to change screen resolutions.

.IP "display [help]"
.B Obtain script help.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
