.\" Manpage for dock.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH dock 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
dock \- Control Dock parameters with ZeamonSH
.SH SYNOPSIS
dock [ showdelay | autohide | magnification | position | addblankspace | addrecentitems | prune | help ]
.SH DESCRIPTION
dock \- Control Dock parameters with ZeamonSH.
.SH OPTIONS

.IP "dock [showdelay] <x.x>"
.B Changes how long the Dock takes to show up when auto-hide is enabled.

.IP "dock [autohide] [YES | NO]"
.B Disable/Enable Dock's auto hide feature.

.IP "dock [magnification] [YES |  NO] "
.B Turn magnification off/on.

.IP "dock [position] [BOTTOM | LEFT | RIGHT]"
.B Change Dock's position to the right, left, bottom  of the screen.

.IP "dock [addblankspace]"
.B Add a blank space (separator) to the Dock.

.IP "dock [addrecentitems]"
.B  Add a stack containg your recent items to the Dock (You can change the stack's type by right clicking on it) 

.IP "dock [prune]"
.B Remove all items from dock

.IP "dock [help]"
.B Obtain script help.

.SH SEE ALSO
Z_Agenda(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
