.\" Manpage for emk.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH emk 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
emk \- kill emacs daemon
.SH SYNOPSIS
emk [-f] [-s target] [-h]
.SH DESCRIPTION
emk \- kill emacs daemon
-f force the killing of the daemon without caring of the buffers

.SH SEE ALSO
.BR emacs(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
