.\" Manpage for extract.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH extract 7 "06 Feb 2020" "1.0" "extract man page"
.SH NAME
extract \- extracts archived files / mounts disk images.
.SH SYNOPSIS
extract <file>
.SH DESCRIPTION
extract \- extracts archived files / mounts disk images.
.SH OPTIONS
The extract does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com.in)
