.\" Manpage for ff.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH ff 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
ff \- Find a file in actual pwd with a pattern in name.
.SH SYNOPSIS
ff <filename_pattern>
.SH DESCRIPTION
ff \- Find a file in actual pwd with a pattern in name.
.SH OPTIONS
The ff does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR find(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
