.\" Manpage for findsuid.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH findsuid 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
findsuid \- Find all SUID files or programs on the system.
.SH SYNOPSIS
findsuid
.SH DESCRIPTION
findsuid \- Find all SUID files or programs on the system other than those that live in /bin and /usr/bin, and output the matches in a friendly and useful format.
.SH OPTIONS
The findsuid does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
