.\" Manpage for findman.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH findman 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
findman \- given a pattern and a man section, show all the matches for that pattern from within all relevant man pages.
.SH SYNOPSIS
findman [section] <cmdpattern> <manpagepattern>
.SH DESCRIPTION
findman \- given a pattern and a man section, show all the matches for that pattern from within all relevant man pages.
.SH OPTIONS
The findman does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
