.\" Manpage for firewall.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH firewall 7 "06 Feb 2020" "MacOS" "MacOS customization"
.SH NAME
firewall \- Configure in kernel firewall (pfctl).
.SH DESCRIPTION
firewall \- Configure in kernel firewall (pfctl).
.SH OPTIONS
The firewall does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli bryan (zucchelli.bryan@gmail.com)
