.\" Manpage for firefox_window.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH firefox_window 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
firefox_window \- Open firefox new window from the command line.
.SH SYNOPSIS
firefox_window
.SH DESCRIPTION
firefox_window \- Open firefox new window from the command line.
.SH OPTIONS
The firefox_window does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
