.\" Manpage for formatdir.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH formatdir 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
formatdir \- Output a directory listing in a friendly and useful format.
.SH SYNOPSIS
formatdir [DIR]
.SH DESCRIPTION
formatdir \- Output a directory listing in a friendly and useful format.
.SH OPTIONS
The formatdir does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
