.\" Manpage for fs.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH fs 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
fs \- Determine size of a file or total size of a directory.
.SH SYNOPSIS
fs <file/directory>
.SH DESCRIPTION
fs \- Determine size of a file or total size of a directory.
.SH OPTIONS
The fs does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR du(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
