.\" Manpage for ftpsyncdown.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH ftpsyncdown 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
ftpsyncdown \- Given a source directory on a remote FTP server, download all the files therein into the current directory.
.SH SYNOPSIS
ftpsyncdown user@host { remotedir }
.SH DESCRIPTION
ftpsyncdown \- Given a source directory on a remote FTP server, download all the files therein into the current directory.
.SH OPTIONS
The ftpsyncdown does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR ftpsyncup(7)   
.BR sftpsync(7)
.BR ssync(7)
.BR xferlog(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
