.\" Manpage for gitx.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH gitx 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
gitx \- The stupid content tracker utility
.SH SYNOPSIS
gitx
.SH DESCRIPTION
gitx \- The stupid content tracker utility
.SH OPTIONS
The gitx does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR git(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
