.\" Manpage for hexToBin.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH hexToBin 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
hexToBin \- Convert hexadecimal numbers to binary
.SH SYNOPSIS
hexToBin <HEXADECIMAL_NUMBER>
.SH DESCRIPTION
hexToBin \- Convert hexadecimal numbers to binary
.SH OPTIONS
The hexToBin does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR decToHex(7)
.BR decToBin(7)
.BR bc(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
