.\" Manpage for host_name.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH host_name 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
host_name \- Set new hostname or get the current hostname information.
.SH SYNOPSIS
host_name [newhostname]
.SH DESCRIPTION
host_name \- Set new hostname or get the current hostname information.
.SH OPTIONS

.IP "host_name"
.B Get the current hostname information (computername, hostname, localhostname and netbiosname)

.IP "host_name [newhostname]"
.B Set a new hostname (computername, hostname, localhostname, netbiosname)

.IP "host_name [help]"
.B only shows this help

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
