.\" Manpage for ii.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH ii 7 "06 Feb 2020" "1.0" "ii man page"
.SH NAME
ii \- Get current host related info.
.SH SYNOPSIS
ii [help]
.SH DESCRIPTION
ii \- Script to get current host related info.
.SH OPTIONS

.IP "ii [help]".
.B Obtain program help info.

.SH BUGS
No known bugs.
.SH AUTHOR
Zuchelli Bryan (zucchelli.bryan@gmail.com.in)
