.\" Manpage for image_crawler.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH image_crawler 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
image_crawler \- Image crawler
.SH SYNOPSIS
image_crawler [baidu|google] <nb_of_image_tocrawl>
.SH DESCRIPTION
image_crawler \- $2 is the number of images you wanna crawl $1 == "baidu" or "google", which is the source of the images you wanna crawl. You could try twice and get the objURLs from baidu and google respectively.
.SH OPTIONS
The image_crawler does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR wget(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
