.\" Manpage for islogin.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH islogin 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
islogin \- Tell if user is graphically log.
.SH SYNOPSIS
islogin
.SH DESCRIPTION
islogin \- Tell if user is graphically log.
.SH OPTIONS
The islogin does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
