.\" Manpage for isroot.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH isroot 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
isroot \- Verify if user have root right.
.SH SYNOPSIS
isroot
.SH DESCRIPTION
isroot \- Verify if user have root right.
.SH OPTIONS
The isroot does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
