.\" Manpage for keychain.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH keychain 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
keychain \- Configure, list and manipulate keychains.
.SH SYNOPSIS
keychain [ lock | unlock | list | help ] 
.SH DESCRIPTION
keychain \- Configure, list and manipulate keychains.
.SH OPTIONS

.IP "keychain [ lock ]"
.B Lock the specified keychain.

.IP "keychain [ unlock ]"
.B Unlock the specified keychain.

.IP "keychain [ list ]"
.B Display or manipulate the keychain search list.

.IP "keychain [ help ]"
.B Obtain script information.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
