.\" Manpage for loginitem.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH loginitem 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
loginitem \- Manage login items from the command line
.SH SYNOPSIS
loginitem [ add | remove | list | help ]
.SH DESCRIPTION
loginitem \- Manage login items from the command line
.SH OPTIONS

.IP "loginitem [add] <LOGINITEMNAME>" 
.B Add login item.

.IP "loginitem [remove] <LOGINITEMNAME>"
.B Remove login item.

.IP "loginitem [list]"
.B List actual login items.

.IP "loginitem [help]"
.B Obtain script help.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
