.\" Manpage for macosinfo.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH macosinfo 7 "06 Feb 2020" "MacOS" "MacOS customization"
.SH NAME
macosinfo \- Give general info about your mac OS X system.
.SH DESCRIPTION
 macosinfo \- Give general info about your mac OS X system.
.SH OPTIONS
The macosinfo does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com.in)
