.\" Manpage for MacOSDefaults.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH MacOSDefaults 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
MacOSDefaults \- To handle defaults database to configure MacOS system.
.SH SYNOPSIS
MacOSDefaults
.SH DESCRIPTION
MacOSDefaults \- To handle defaults database to configure MacOS system.
.SH OPTIONS
The MacOSDefaults does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
