.\" Manpage for maverick-hacks.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH maverick-hacks 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
maverick-hacks \- Hacks for Mac OS X maverick versions
.SH SYNOPSIS
maverick-hacks
.SH DESCRIPTION
maverick-hacks \- Hacks for Mac OS X maverick versions
.SH OPTIONS
The maverick-hacks does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
