.\" Manpage for menusage.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH menusage 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
menusage \- Memory overview.
.SH SYNOPSIS
menusage
.SH DESCRIPTION
menusage \- Memory overview.
.SH OPTIONS
The menusage does not take any options.
However, you can supply one to the God of man.
.BR ps(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
