.\" Manpage for network.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH network 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
network \- Handle and give some netork informations
.SH SYNOPSIS
network [ ls | list | location | help ]
.SH DESCRIPTION
network \- Handle and give some netork informations
.SH OPTIONS

.IP "network [ls]"
.B List network interfaces.

.IP "network [location]"
.B Get current location.

.IP "network [location] [ls]"
.B List locations.

.IP "network [loccation] [create] <XYZ>"
.B Create a location.

.IP "network [loccation] [delete] <XYZ>"
.B Delete a location.

.IP "network [loccation] [switch] <XYZ>"
.B Switch location.

.IP "network [help]"
.B Obtain help script.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
