.\" Manpage for notification.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH notification 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
notification \- Get status, enable and disable notification center.
.SH SYNOPSIS
notification [ status | enable | disable | help ]
.SH DESCRIPTION
notification \- Get status, enable and disable notification center.
.SH OPTIONS

.IP "notification [status]"
.B Get the current status.

.IP "notification [enable | disable]"
.B Enable the notification center.

.IP "notification [help]"
.B Obtain script help.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
