.\" Manpage for ntp.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH ntp 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
ntp \- Set Network timme (NTP) from CLI.
.SH SYNOPSIS
ntp [ status | enable | disable | set | help ]
.SH DESCRIPTION
ntp \- Set Network timme (NTP) from CLI.
.SH OPTIONS

.IP "ntp [status]"
.B Status of the network time service

.IP "ntp [enable]"
.B Enable clock to use network time

.IP "ntp [disable]"
.B Disable clock to use network time

.IP "ntp [set]" <timehost1.net.sap.corp>
.B Set network time server

.IP "ntp [help]"
.B Obtain script help.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
