.\" Manpage for pd_dot.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH pd_dot 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
pd_dot \- Generate draw graph(s) from a DOT file
.SH SYNOPSIS
pd_dot <file.dot>
.SH DESCRIPTION
pd_dot \- Generate draw graph(s) from a DOT file
.SH OPTIONS
The pd_dot does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
