.\" Manpage for phpserver.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH phpserver 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
phpserver \- Start a PHP server from a directory, optionally specifying the port
.SH SYNOPSIS
phpserver
.SH DESCRIPTION
phpserver \- Start a PHP server from a directory, optionally specifying the port
.SH OPTIONS
The phpserver does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR php(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
