.\" Manpage for port.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH portAuto7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
portAuto \- Script collection to manage MacPorts
.SH SYNOPSIS
port
.SH DESCRIPTION
portAuto \- Script collection to manage MacPorts
.SH OPTIONS
to finish
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)

