.\" Manpage for printer.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH printer 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
printer \- Control printer with CLI.
.SH SYNOPSIS
printer [ settings | name | queue | drivers | web | help ]
.SH DESCRIPTION
printer \- Control printer with CLI.
.SH OPTIONS

.IP "printer [settings]"
.B Printer settings

.IP "printer [name]"
.B Display printer names on system

.IP "printer [queue]"
.B Display items in printer queue on system

.IP "printer [drivers]"
.B Display all printer drivers

.IP "printer [web]"
.B Enable and show web interface

.IP "printer [help]"
.B Obtain script help.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
