.\" Manpage for prompt_bz_setup.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH man 7 "06 Feb 2020" "1.0" "prompt_bz_setup man page"
.SH NAME
prompt_bz_setup \- Laptop oriented zsh theme prompt
.SH SYNOPSIS
prompt_bz_setup
.SH DESCRIPTION
. prompt_bz_setup : zsh prompt theme
The prompt_bz_setup does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
your Name (zucchelli.bryan@gmail.com.in)
