.\" Manpage for prompt_pure_setup.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH prompt_pure_setup 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
prompt_pure_setup \- Pure Zaemonsh prompt theme.
.SH DESCRIPTION
prompt_pure_setup \- Pure Zaemonsh prompt theme.
prompt_ResetAll_setup(7), prompt_default_setup(7), prompt_kerbaugh_setup(7), prompt_redhat_setup(7), prompt_adam1_setup(7), prompt_dotphiles_setup(7), prompt_liquidprompt_setup(7), prompt_restore_setup(7), prompt_adam2_setup(7), prompt_elite2_setup(7), prompt_magicmace_setup(7), prompt_simple_setup(7), prompt_sorin_setup(7), prompt_elite_setup(7), prompt_nicoulaj_setup(7), prompt_bart_setup(7), prompt_eriner_setup(7), prompt_off_setup(7), prompt_steeef_setup(7), prompt_bigfade_setup(7),prompt_fade_setup(7), prompt_oliver_setup(7), prompt_suse_setup(7),prompt_bz_setup(7), prompt_fire_setup(7), prompt_asyd_setup(7), prompt_walters_setup(7), prompt_clint_setup(7), prompt_gitster_setup(7), prompt_pws_setup(7), prompt_zefram_setup(7)
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
