.\" Manpage for rfc.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH rfc 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
rfc \- Search and read (local) RFCs
.SH SYNOPSIS
rfc
.SH DESCRIPTION
rfc \- Search and read (local) RFCs. "rfc --find MIME" should display the first line of the descriptions for all RFCs regarding MIME, along with # their numbers.
.SH OPTIONS

.IP rfc --find foobar
.B Search for a RFC

.IP rfc 1036
.B Read RFC by number (i. e. RFC 1036)

.IP rfc
.B Read the RFC index

.SH SEE ALSO
.BR lynx(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
