.\" Manpage for rmall.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH rmall 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
rmall \- Erase all file not folder in current tree directory.
.SH SYNOPSIS
rmall <DIRECTORY>
.SH DESCRIPTION
rmall \- Erase all file not folder in current tree directory.
.SH OPTIONS
The rmall does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
