.\" Manpage for screenn.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH screenn 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
screenn \- Function to settab to show the named process running and then reset with settab for command screen.
.SH SYNOPSIS
screenn
.SH DESCRIPTION
screenn \- Function to settab to show the named process running and then reset with settab for command screen.
.SH OPTIONS
The screenn does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR screen(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
