.\" Manpage for shutdown.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH man 7 "06 Feb 2020" "MacOS" "MacOS Darwin ZaemonSH customization"
.SH NAME
shutdown \- Shutdown computer on Darwin.
.SH SYNOPSIS
shutdown [-f|--force|help]
.SH DESCRIPTION
shutdown \- Wrapper script to shutdown computer on Darwin.
.SH OPTIONS

.IP "shutdown"
.B Shutdown computer (needs confirmation).

.IP "shudtown [-f|--force]"
.B  Shutdown computer (without confirmation).

.IP "shutdown [help]"
.B Obtain program help info.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
