.\" Manpage for sleeep.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH sleeep 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
sleeep \- Put your computer into sleep mode.
.SH SYNOPSIS
sleeep [ until | now | help ]
.SH DESCRIPTION
sleeep \- Put your computer into sleep.
.SH OPTIONS

.IP "sleeep [until] <SECONDS>"
.B Sleep until 3600 seconds.

.IP "sleeep [until] <SCRIPTNAME>"
.B Sleep until the script ends.

.IP "sleeep [now]"
.B Put in sleep mode immediately.

.IP "sleeep [help]"
.B Obtain script information.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
