.\" Manpage for spotlight.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH spotlight 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
spotlight \- Control spotlight config with CLI.
.SH SYNOPSIS
spotlight [ IndexingStatus | On | Off | LockIndex | PublishIndex | RemoveIndex | RemoveStore | help ]
.SH DESCRIPTION
spotlight \- Control spotlight config with CLI.
.SH OPTIONS

.IP "spotlight [IndexingStatus]"
.B Show Spotlight index status.

.IP "Spotlight [on | off]"
.B Turn Spotlight indexing on/off.

.IP spotlight [LockIndex]
.B Set volume to never be indexed.

.IP spotlight [PublishIndex]
.B Publish indexes to drive.

.IP spotlight [RemoveIndex]
.B Remove Spotlight indexes.

.IP spotlight [RemoveStore]
.B Remove Spotlight store.'

.IP spotlight [help]
.B Obtain script help.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
