.\" Manpage for termMultiTab.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH termMultiTab 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
termMultiTab \- Launch several tab with to associate command.
.SH SYNOPSIS
termMultiTab <COMMAND1> <COMMAND2> ...
.SH DESCRIPTION
termMultiTab \- Launch several tab with to associate command.
.SH OPTIONS
The termMultiTab does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR termWindow(7), tab(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
