.\" Manpage for timezone_handle.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH timezone_handle 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
timezone_handle \- Get, set and list available timezone(s).
.SH SYNOPSIS
timezone_handle [ list | ls | set | help ]
.SH DESCRIPTION
timezone_handle \- Get, set and list available timezone(s).
.SH OPTIONS

.IP "timezone_handle" 
.B Get current timezone.

.IP "timezone_handle [ls]"
.B List available timezones.

.IP timezone_handle [set] <Europe/Berlin>      
.B Set timezone.

.IP "timezone_handle [help]"
.B Obtain script help.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)

