.\" Manpage for toggle_spaces.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH toggle_spaces 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
toggle_spaces \- Turn space on/off.
.SH SYNOPSIS
toggle_spaces
.SH DESCRIPTION
toggle_spaces \- Turn space on/off.
.SH OPTIONS
The toggle_spaces does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR switcher(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
