.\" Manpage for unidecode.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH unidecode 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
unidecode \- Decode \x{ABCD}-style Unicode escape sequences.
.SH SYNOPSIS
unidecode <string>
.SH DESCRIPTION
unidecode \- Decode \x{ABCD}-style Unicode escape sequences
.SH OPTIONS
The unidecode does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR perl(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
