.\" Manpage for update_supervisor.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH update_supervisor 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
update_supervisor \- Create a copy of iTerm called iTermVisor which will run in background on login, only uses visor.
.SH SYNOPSIS
update_supervisor
.SH DESCRIPTION
update_supervisor \- Create a copy of iTerm called iTermVisor which will run in background on login, only uses  visor.
.SH OPTIONS
The update_supervisor does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
