.\" Manpage for web_dev.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH web_dev 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
web_dev \- Web Development Utilities
.SH SYNOPSIS
web_dev
.SH DESCRIPTION
web_dev \- Web Development Utilities
.SH OPTIONS
The web_dev does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
