.\" Manpage for webspell.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH webspell 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
webspell \- Use the 'aspell' feature + lynx to spell check either a Web page URL or a file.
.SH SYNOPSIS
webspell file|URL
.SH DESCRIPTION
webspell \- Use the 'aspell' feature + lynx to spell check either a Web page URL or a file.

Inevitably you'll find that there are words it flags as wrong, but you think are fine. Simply save them in a file, one-per-line, and ensure that 'okaywords' points to that file.

.SH OPTIONS
The webspell does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR lynx(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
