.\" Manpage for wifi.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH wifi 7 "06 Feb 2020" "ZaemonSH MacOS" "MacOS ZaemonSH customization"
.SH NAME
wifi \- Interact with your wifi configuration and informations.
.SH SYNOPSIS
wifi [ status | scan | showpassword | history | off | on | connect | help ]
.SH DESCRIPTION
wifi \- Interact with your wifi configuration and informations.
.SH OPTIONS

.IP "wifi [status]"
.B Give wifi status.

.IP "wifi [scan]"
.B Scan wifi

.IP "wifi [showpassword] <ESSID>" 
.B Show wifi network password (default: current).

.IP "wifi [history]"
.B Give wifi connection history.

.IP "wifi [ off | on ]"
.B Turn off/on your wifi.

.IP "wifi [connect] <ESSID> <PASSWORD>"
.B Join a wifi network.

.IP "wifi [help]"
.B Obtain script help.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
