.\" Process this file with
.\" groff -man -Tascii foo.
.\"
.TH Z_Addagenda 7 "Feb 02, 2020" "Mac OS X" "Mac OS X Darwin customization"
.SH NAME
.B Z_Addagenda 
\- A reminder for your events

.SH SYNOPSIS
.B Z_Addagenda

.SH DESCRIPTION
.B Z_Addagenda
The Unix Reminder Service.Add new events to
.B Z_Agenda

.SH OPTIONS
.B Z_Addagenda
does not take any options.
However, you can supply one to the God of man.

.SH SEE ALSO
.BR Z_Agenda (7)

.SH BUGS
No known bugs.

.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com.in)
