.\" Manpage for Z_Agenda.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_Agenda 7 "ZaemonSH core customization" "Z_Agenda(7)"  "July 9 2020" 

.SH NAME
Z_Agenda \- Scan through the user's agenda file
.SH SYNOPSIS
Z_Agenda
.SH DESCRIPTION
. Z_Agenda: The Unix Reminder Service
Scan through the user's .agenda file to see if there
are any matches for the current or next day
.SH OPTIONS
The Z_Agenda does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
Z_Addagenda(7)
.SH BUGS
No known bugs.
.SH AUTHOR
your Name (zucchelli.bryan@gmail.com)
