.\" Manpage for Z_Restart.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_Restart 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_Banner \- Show banner at ZeamonSH starting.
.SH SYNOPSIS
Z_banner [ON|OFF]
.SH DESCRIPTION
Z_Banner \- Show banner at ZeamonSH starting.
.SH OPTIONS

.IP "Z_Banner [ON|OFF]"
.B Activate/Deactivate banner at ZeamonSH starting.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
