.\" Manpage for Z_CleanOSXSHIT.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_CleanOSXSHIT 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_CleanOSXSHIT \- Remove Osx annoying files on linux.Remove hidden DS.Store, .localized files.
.SH SYNOPSIS
Z_CleanOSXSHIT
.SH DESCRIPTION
Z_CleanOSXSHIT \- Remove Osx annoying files on linux.Remove hidden DS.Store, .localized files.
.SH OPTIONS
The Z_CleanOSXSHIT does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
