.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH Z_Configure_zaemonsh_templates_pashua 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B Z_Configure_zaemonsh_templates_pashua 
\-  invoked by Z_Configure_zaemonsh_templates 
.SH SYNOPSIS
.B Z_Configure_zaemonsh_templates_pashua
.SH DESCRIPTION
.B Z_Configure_zaemonsh_templates_pashua
is invoked by the Z_Configure_zaemonsh_templates function. It invokes the Pashua GUI version useful for larger displays. This is the default.
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR Z_Configure_zaemonsh_templates (7)


