.\" Manpage for Z_CompletionWhereis.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_CompletionWhereis 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_CompletionWhereis \-  Locate and view completions.
.SH SYNOPSIS
Z_CompletionWhereis <COMPLETIONNAME>
.SH DESCRIPTION
Z_CompletionWhereis \-  Locate and view completions.
.SH OPTIONS
The Z_CompletionWhereis does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
Z_CompFctList(7), Z_CompletionEdit(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
