.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH Z_Configure_zaemonsh_templates 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B Z_Configure_zaemonsh_templates 
\- invokes the Z_Configure_zaemonsh_templates gui function to assist in configuring the zsh shell
customization templates.
.SH SYNOPSIS
.B Z_Configure_zaemonsh_templates
.SH DESCRIPTION
.B Z_Configure_zaemonsh_templates
invokes the Z_Configure_zaemonsh_templates gui function to assist in configuring the zsh shell customization templates. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR zaemonsh-templates (7)
