.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH Z_Configure_zaemonsh_templates_ascli 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization"
.SH NAME
Z_Configure_zaemonsh_templates_ascli \- It invokes the shellscript CLI version.
.SH SYNOPSIS
.B Z_Configure_zaemonsh_templates_ascli
.SH DESCRIPTION
.B Z_Configure_zaemonsh_templates_ascli
is invoked by the Z_Configure_zaemonsh_templates function. It invokes the shellscript CLI version.
.SH "SEE ALSO"
.BR Z_Configure_zaemonsh_templates (7), Z_Configure_zaemonsh_templates_asgui (7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
