.\" Manpage for Z_CompletionEdit.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_CompletionEdit 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_CompletionEdit \- Manipulate and edit ZaemonSH completion. 
.SH SYNOPSIS
Z_CompletionEdit [help]
.SH DESCRIPTION
Z_CompletionEdit \- Script to edit ZaemonSH completion.
.SH OPTIONS

.IP "Z_CompletionEdit [help]".
.B Obtain program help info.

.SH SEE ALSO
Z_CompletionWhereis(7), Z_CompFctList(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zuchhelli Bryan (zucchelli.bryan@gmail.com)