.\" Manpage for Z_FunctionPluginsExtraLoop.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_FunctionPluginsExtraLoop 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
Z_FunctionPluginsExtraLoop \- Loop through extra ZaemonSh plug-ins to view their contents.
.SH SYNOPSIS
Z_FunctionPluginsExtraLoop
.SH DESCRIPTION
Z_FunctionPluginsExtraLoop \- Loop through extra ZaemonSh plug-ins to view their contents.
.SH OPTIONS
The Z_FunctionPluginsExtraLoop does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
