.\" Manpage for Z_FunctionAdd.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_FunctionAdd 7 "06 Feb 2020" "ZaemonSH Universal" "Universal ZaemonSH customization"
.SH NAME
Z_FunctionAdd \- Create, load, activate, function from ZaemonSH.
.SH SYNOPSIS
Z_FunctionAdd
.SH DESCRIPTION
Z_FunctionAdd \- Create, load, activate, function from ZaemonSH.
.SH OPTIONS
The Z_FunctionAdd does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
.BR Z_FunctionDel(7)
.BR Z_FunctionUtil(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
