.\" Manpage for Z_FunctionWhereis.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_FunctionWhereis 7 "06 Feb 2020" "1.0" "ZaemonSH function"
.SH NAME
Z_FunctionWhereis \- Locate and view Zaemonsh functions.
.SH DESCRIPTION
Z_FunctionWhereis \- Locate and view Zaemonsh functions.
.SH SEE ALSO
Z_FunctionUtil(7), Z_FunctionEdit(7)
.SH BUGS
No known bugs.
.SH AUTHOR
your Name (zucchelli.bryan@gmail.com)
