.\" Manpage for Z_FunctionEdit.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_FunctionEdit 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_FunctionEdit \- Manipulate and edit ZaemonSH function. 
.SH SYNOPSIS
Z_FunctionEdit [help]
.SH DESCRIPTION
Z_FunctionEdit \- Script to edit ZaemonSH Function.
.SH OPTIONS

.IP "Z_FunctionEdit [help]".
.B Obtain program help info.

.SH SEE ALSO
Z_FunctionWhereis(7), Z_FunctionAdd(7), Z_FunctionDel(7), Z_FunctionPluginsExtraLoop(7), Z_FunctionBySubcat(7), Z_FunctionUtil(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zuchhelli Bryan (zucchelli.bryan@gmail.com)
