.\" Manpage for Z_Grml.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_Grml 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_Grml \- Activate/desactivate grml script on zaemonsh.
.SH SYNOPSIS
Z_Grml
.SH DESCRIPTION
Z_Grml \- Activate/desactivate grml script on zaemonsh.
.SH OPTIONS

.IP "Z_Grml [on]"
.B Enable Syntax hightligthing plug-in.

.IP "Z_Grml [off]"
.B Disable Syntax hightligthing plug-in.

.IP "Z_Grml [help]"
.B Obtain script information.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
