.\" Manpage for _Z_Host_user_completion_settings.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH _Z_Host_user_completion_settings 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
_Z_Host_user_completion_settings \- Z_Host_setup, Z_Host_setup_cli, Z_User_setup, Z_User_setup_cli variables declaration.
.SH SYNOPSIS
_Z_Host_user_completion_settings
.SH DESCRIPTION
_Z_Host_user_completion_settings \- Z_Host_setup, Z_Host_setup_cli, Z_User_setup, Z_User_setup_cli variables declaration.
.SH OPTIONS
The _Z_Host_user_completion_settings does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
Z_Host_setup(7), Z_Host_setup_cli(7), Z_User_setup(7), Z_User_setup_cli(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
