.TH Z_My_mac_applications 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B Z_My_mac_applications
\- helper function for _Z_Open, i.e., "Z_Open -a" completions

.SH SYNOPSIS
Z_My_mac_applications

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
