.\" Manpage for Z_Notes.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_Notes 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_Notes \- handle notes
.SH SYNOPSIS
Z_Notes [list | find | html-view | view | all-tags | export]
.SH DESCRIPTION
Z_Notes \- Tool for searching and manipulating "notes" stored in markdown-formatted text files
.SH OPTIONS

.IP "Z_Notes [list]"
.B Lists all of the note filenames.

.IP "Z_Notes [find]"
.B Searches the notes that contain a particular string.

.IP "Z_Notes [html-view]"
.B Converts a markdown formatted note into HTML. Opens in browser.

.IP "Z_Notes [view]"
.B View note.

.IP "Z_Notes [all-tags]"
.B List all of the tags used in all notes.

.IP "Z_Notes [export]"
.B Export some notes as HTML into the directory
.SH SEE ALSO
Z_Note(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
