.\" Manpage for Z_OptList.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_OptList 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_OptList \- List of actives/inactives distributed zsh functions
.SH SYNOPSIS
Z_OptList
.SH DESCRIPTION
Z_OptList \- List of actives/inactives distributed zsh functions
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
