.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_OsxVersTest 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_OsxVersTest \- Test compability osx versions script.
.SH SYNOPSIS
Z_OsxVersTest [-f|-b] <OSX_VERSION_NUMBER>
.SH DESCRIPTION
 Z_OsxVersTest \- Test compability osx versions script.
.SH OPTIONS

.IP "Z_OsxVersTest [-f]"
.B verbose foreground version.

.IP "Z_OsxVersTest [-b]"
.B Silently sending 1 versions compatible or 0 not compatible.

.IP "Z_OsxVersTest [help]"
.B Obtain program help info.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
