.\" Manpage for Z_Search.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_Search 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_Search \- Completion for Z_Search to Search for patterns on $ZDOT, $P_NATFCTDIR or on $P_ZDOTCONFDIR folder
.SH SYNOPSIS
Z_Search [ onconfig | onzdot | help ]
.SH DESCRIPTION
Z_Search \- Completion for Z_Search to Search for patterns on $ZDOT, $P_NATFCTDIR or on $P_ZDOTCONFDIR folder
.SH OPTIONS

.IP "Z_Search [ onconfig ] <pattern>"
.B Search pattern on config files.

.IP "Z_Search [ onzdot ] <pattern>"
.B Search pattern on $ZDOT.

.IP "Z_Search [ onnatf ] <pattern>"
.B Search pattern on native directory function.

.IP "Z_Search [ help ]"
.B Obtain program help info.

.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli bryan (zucchelli.bryan@gmail.com)
