.\" Manpage for Z_Settings.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_Settings 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_Settings \- Show all ZaemonSH settings.
.SH DESCRIPTION
Z_Settings \- Show all ZaemonSH settings.
.SH OPTIONS
The Z_Settings does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
