.\" Manpage for Z_SkelC.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_ShelC 7 "06 Feb 2020" "1.0" "Z_SkelC man page"
.SH NAME
Z_SkelC \- Launch a skel of completion to edit.
.SH SYNOPSIS
Z_SkelC <function_name>
.SH DESCRIPTION
Z_SkelC \- Launch a skel of completion to edit.
.SH OPTIONS
The Z_SkelC does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
