.\" Manpage for Z_Switch_prompt_ascli.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_Switch_prompt_ascli 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_Switch_prompt_ascli \- Function to permit the user to switch the prompt easily.
.SH SYNOPSIS
Z_Switch_prompt_ascli
.SH DESCRIPTION
Z_Switch_prompt_ascli \- Function to permit the user to switch the prompt easily.
.SH OPTIONS
The Z_Switch_prompt_ascli does not take any options.
However, you can supply one to the God of man.
.SH SEE ALSO
Z_Switch_prompt(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
