.\" Manpage for Z_Whatsnew.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH Z_Whatsnew 7 "06 Feb 2020" "ZaemonSH" "ZaemonSH customization"
.SH NAME
Z_Whatsnew \- Compare ZaemonSH directory with template to view news.
.SH DESCRIPTION
Z_Whatsnew \- Compare ZaemonSH directory with template to view news.
.SH OPTIONS
The Z_Whatsnew does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
