.\" Manpage for zoneinfo.
.\" Contact bryan.zucchellik@gmail.com to correct errors or typos.
.TH zoneinfo 7 "06 Feb 2020" "ZaemonSH Universal" "universal ZaemonSH customization"
.SH NAME
zoneinfo \- Show the current time in the specified timezone or geographic zone.
.SH SYNOPSIS
zoneinfo
.SH DESCRIPTION
zoneinfo \- Show the current time in the specified timezone or geographic zone. Without any argument, show UTC/GMT. Use the word "list" to see a list of known geographic regions Note that it's possible to match a zone directory (a region) but that only timezone files are valid specifications.
.SH OPTIONS
The zoneinfo does not take any options.
However, you can supply one to the God of man.
.SH BUGS
No known bugs.
.SH AUTHOR
Zucchelli Bryan (zucchelli.bryan@gmail.com)
