#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2019. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# dashboard :
# Wrapper script to control dashboard on darwin.

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 15/10/2017 :
#  • Modify script presentation.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
local CLEAR ECHO GREP KILLALL DEFAULTS VERSION FCT_NAME DTST help disable enable status banner 

VERSION="0.0.1"
FCT_NAME="$(echo $0)"

# Define some local command
CLEAR="$(command clear)"
ECHO="$(command echo)"
GREP="$(command grep)"
KILLALL="$(command killall)"
DEFAULTS="$(command defaults)"

DTST=$(DEFAULTS read com.apple.dashboard 2>/dev/null | $GREP "mcx-disabled" | $GREP "0")

#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
echo  "${RED}"
    cat<<__EOF__
    usage:  dashboard [ status | enable | disable | help ]

    Examples:
      Dashboard  status                               # dashboard status
      Dashboard  enable                               # enable dashboard 
      Dashboard  disable                              # disable dashboard
__EOF__
echo  "${NC}" 
}

disable(){
if [ -z "$1" ]; then
    $DEFAULTS write com.apple.dashboard mcx-disabled -boolean YES 2>/dev/null # "mcx-disabled" = 1;
    $KILLALL Dock
    builtin echo "${GREEN}Dashboard is disable now.${NC}"
    return 0
fi
}

enable(){
if [ -z "$1" ]; then    
    $DEFAULTS write com.apple.dashboard mcx-disabled -boolean NO # "mcx-disabled" = 0;
    $KILLALL Dock
    builtin echo  "${RED}Dashboard is disable now.${NC}"
    return 0
fi
}

status(){
#defaults read com.apple.dashboard | grep "mcx-disabled" | sed 's/.*=//' | sed 's/;.*//'
if [ $DTST ]; then
    builtin echo "${GREEN}Dashboard status : enabled.${NC}"
else
    builtin echo "${RED}Dashboard status : disabled.${NC}"
fi
}

banner () {
  clear
  echo "${NC}"
  echo " ###################################################################################################"
  echo " #                                                                                                 #"
  echo " #     ${GREEN}This is ${RED}$FCT_NAME : ${YEL}$VERSION FOR $OSTYPE ${NC}                                                   #"
  echo " #     CopyL®®v 2019, Zucchelli Bryan                                                              #"
  echo " #                                                                                                 #"
  echo " #     Unless required by applicable law or agreed to in writing, software                         #"
  echo " #     distributed under the License is distributed on an "AS IS" BASIS,                             #"
  echo " #     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                    #"
  echo " #     See the License for the specific language governing permissions and                         #"
  echo " #     limitations under the License.                                                              #"
  echo " #                                                                                                 #"
  echo " ###################################################################################################"
  echo ""
}

#----------------------------------------------------------------------------------------#
#                                       SCRIPT
#----------------------------------------------------------------------------------------#
banner
case $1 in
    help)
        help
        ;;
    status)
        shift
        status "$*"
        ;;
    enable)
        shift
        enable "$*"
        ;;
    disable)
        shift
        disable "$*"
        ;;
    *)
        help
        ;;
esac
