#! /usr/bin/env zsh -f

######################################################################################################
#                                                                                                    #
#    ZAEMONSH Created by Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2017.         #
#    Copyright (c) 2019. All rights reserved.                                                        #
#    Hardly inspired by zsh-templates created by William Scott on May 11, 2007.                      #
#    Copyright (c) 2007. All rights reserved.                                                        #
#                                                                                                    #
#    This program is free software; you can redistribute it and/or modify it under the terms of      #
#    the GNU General Public License as published by the Free Software Foundation; either             #
#    version 2 of the License, or (at your option) any later version.                                #
#                                                                 									 # 
#    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY ;      #
#    without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.       #
#    See the GNU General Public License for more details.                                  			 #
#                                                        											 #
#    You should have received a copy of the GNU General Public License along with this program ;     #
#    if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,           #
#    Boston,  MA 02110-1301 USA                    													 #
#                                                                                                    #
#    cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                                       #
#                                                                                                    #
######################################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# getstats :
# Every 'n' minutes, grab netstats values (via crontab) :

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 13/0/2018 :
#  • Modify function presentation.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
#######################
## COMMAND VARIABLES ##
#######################
local VERSION FCT_NAME

VERSION="0.0.1"
FCT_NAME="Z_getstats"

logfile="/var/log/netstat.log"
temp="/tmp/getstats.tmp" 

#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
  cat<<__EOF__
  ${RED}
    usage:  [  ]

    Examples:
                                                 # .

  ${NC}
__EOF__
}



#----------------------------------------------------------------------------------------#
#                                       SCRIPT
#----------------------------------------------------------------------------------------#
banner
trap "/bin/rm -f $temp" 0

( echo -n "time=$(date +%s);"

netstat -s -p tcp > $temp

local sent="$(grep 'packets sent' $temp | cut -d\  -f1 | sed 's/[^[:digit:]]//g')"
local resent="$(grep 'retransmitted' $temp | cut -d\  -f1 | sed 's/[^[:digit:]]//g')"
local received="$(grep 'packets received$' $temp | cut -d\  -f1 | sed 's/[^[:digit:]]//g')"
local dupacks="$(grep 'duplicate acks' $temp | cut -d\  -f1 | sed 's/[^[:digit:]]//g')"
local outoforder="$(grep 'out-of-order packets' $temp | cut -d\  -f1 | sed 's/[^[:digit:]]//g')"
local connectreq="$(grep 'connection requests' $temp | cut -d\  -f1 | sed 's/[^[:digit:]]//g')"
local connectacc="$(grep 'connection accepts' $temp | cut -d\  -f1 | sed 's/[^[:digit:]]//g')"
local retmout="$(grep 'retransmit timeouts' $temp | cut -d\  -f1 | sed 's/[^[:digit:]]//g')"

echo -n "snt=$sent;re=$resent;rec=$received;dup=$dupacks;"
echo -n "oo=$outoforder;creq=$connectreq;cacc=$connectacc;"
echo "reto=$retmout"

) >> $logfile

return 0
