#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2019. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# breww :
# Homebrew utility.

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#
# 11/01/2018 :
# • Upadte corresponding completion.
# 21/08/2019 ;
# • Test connection before all.
# • test script.
# 2020-07-30 :
# • Finish script

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 04/01/2018 :
#  • Modify function presentation.
# 11/01/2018 :
# • Merge all past functions related to brew (brew-diff brewInstall ) with breww one.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
#######################
## COMMAND VARIABLES ##
#######################
local VERSION FCT_NAME

VERSION="0.0.1"
FCT_NAME="$(echo $0)"

#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
  cat<<__EOF__
  ${RED}
    usage:  [  ]

    Examples:
                                                 # .

  ${NC}
__EOF__
}

brew_install(){
  # Install homebrew if it isn't already installed.
  if ! hash brew 2> /dev/null; then
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  # Use latest package definitions
  brew update

  # Upgrade old packages (if any)
  brew upgrade

  # Install essential homebrews
  brew install fish --HEAD
  brew install hub
  brew install macvim --with-lua --custom-icons --override-system-vim --HEAD
  brew install python
  brew install ruby
  brew install ssh-copy-id
  brew install the_silver_searcher
  brew install tree
  brew install wget

  # Install essential casks
  brew install caskroom/cask/brew-cask
  brew cask install caffeine
  brew cask install dropbox
  brew cask install flux
  brew cask install google-chrome
  brew cask install hazel
  brew cask install kaleidoscope
  brew cask install mplayerx
  brew cask install skype
  brew cask install spotify
  brew cask install steam
  brew cask install the-unarchiver
  brew cask install torbrowser
  brew cask install trim-enabler
  brew cask install utorrent
  brew cask install mactex

  # Remove outdated versions from the Cellar
  brew cleanup

  # Link .app files into /Applications
  brew linkapps
}

brew_diff(){
  # Figure out what was installed manually but hasn't been added
  # to my dotfile list of taps, formulas or casks
  diff <(brew tap) $ZSH/homebrew/taps
  diff <(brew leaves) <(cut -d ' ' -f1 $ZSH/homebrew/formulas)
  diff <(brew cask list) $ZSH/homebrew/casks 
}

cask_list(){
  echo "
    alfred
    appcleaner
    appcode
    cargo
    github
    google-chrome
    hex-fiend
    hipchat
    hockeyapp
    imageoptim
    intellij-idea
    iterm2
    java
    kaleidoscope
    league-of-legends
    paintbrush
    qlstephen
    rust
    sketch
    sonos
    spectacle
    spotify
    spotify-notifications
    transmission
    tunnelblick
    vagrant
    virtualbox
    vlc
  "
}

dot(){
  export ZSH=$HOME/.dotfiles
  # Set OS X defaults
  $ZSH/osx/set-defaults.sh

  # Upgrade homebrew
  brew update

  # Install homebrew packages
  $ZSH/homebrew/install.sh 2>&1
}

formulas(){
  echo "
    binutils
    brew-cask
    brew-desc
    cmake
    colordiff
    coreutils
    curl
    fzf
    git
    gradle
    gradle110
    hub
    icu4c
    imagemagick
    jq
    mercurial
    pngcrush
    pngquant
    pv
    rbenv
    ruby-build
    the_silver_searcher
    tree
    vim --override-system-vim --with-lua --with-luajit
    wget
    xcproj
    xctool
    zsh-completions
  "
}

####
install_brewfiles() {
    while read tap; do
        brew tap $tap
    done < "${DIR}/taps"

    while read formula; do
        brew install $formula
    done < "${DIR}/formulas"
}

install_caskfiles() {
    while read cask ; do
        brew cask install $cask
    done < "${DIR}/casks"

    # Ensure alfred finds all the installed casks
    brew cask alfred link
}

main() {
    brew update
    brew upgrade

    install_brewfiles
    install_caskfiles

    brew cleanup
    brew doctor
}
###

taps(){
  caskroom/cask
  caskroom/fonts
  homebrew/dupes
  homebrew/versions
  telemachus/desc
}

#-------------------------------------------------------------------------------------------#
#                                              SCRIPT
#-------------------------------------------------------------------------------------------#
banner


