#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2020. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# Z_AliasWhereis v0.0.2 :
# Locate and view zaemonSH aliases.

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#
# 10/10/2017 :
# • Debug script and clean. 
# • Problem with function usage.
# • Problem with multiple result.

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 28/09/2017 :
# • Unify script presentation.
# • Integrated alias path variables from $ZDOT/zshrc.d/131_environment.variables.additional.zsh
# • Add variable command.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
local VERSION  COMTOSEARCH ALIASMAINLIST ALIASADDILIST ALIASDARWINLIST ALIASLINUXLIST P_GRMLALIASFILE ALIASGRMLLIST


VERSION="v0.0.2"
FCT_NAME="Z_AliasWhereis"

COMTOSEARCH="${@}"

###############################################
###             MAIN ALIAS LIST
###############################################
ALIASMAINLIST="$(grep  "alias ${COMTOSEARCH}=" "${P_MAINALIASFILE}"  | grep -E "=" | sed 's/^[ \t]*//;s/[ \t]*$//')"
ISIN_P_MAINALIASFILEFILE=''

###############################################
###           ADDITIONALS ALIAS LIST
###############################################
#ALIASADDILIST="$(grep "alias ${COMTOSEARCH}=" "${P_ADDIALIASFILE}"  | sed 's/alias//' | grep "=" | sed 's/.*://' | grep "alias"  | sed 's/^[ \t]*//;s/[ \t]*$//' | grep -E '^alias '  | sed 's/.*alias//' | grep '=' )"
ALIASUNILIST="$(grep "alias ${COMTOSEARCH}=" "${P_UNIALIASFILE}"  | grep -E "=")"	
ISIN_P_ADDIALIASFILE=''

###############################################
###             DARWIN ALIAS LIST
###############################################
ALIASDARWINLIST="$(grep "alias ${COMTOSEARCH}=" "${P_DARWALIASFILE}"  | grep -E "=")"	
ISIN_P_DARWALIASFILE=''

###############################################
###              LINUX ALIAS LIST
###############################################
ALIASLINUXLIST="$(grep "alias ${COMTOSEARCH}=" "${P_LINUXALIASFILE}"  | grep -E "=")"	
ISIN_P_LINUXALIASFILE=''
###


###############################################
###              GRML ALIAS LIST
###############################################
P_GRMLALIASFILE=$ZDOT/zshrc.d/local-functions/etc/grmlrc/grmlrc
ALIASGRMLLIST="$(grep "alias ${COMTOSEARCH}=" "${P_GRMLALIASFILE}"  | grep -E "=")"
ISIN_P_GRMLALIASFILE=''

###
P_PLUGINSALIASFILE=$ZDOT/plugins
ALIASPLUGINSLIST="$(grep -rn "alias $COMTOSEARCH=" ${P_PLUGINSALIASFILE}  | sed 's/.*://' |  grep -E "=")"
# ALIASPLUGINSPATH=${PLUGINSALIASRES%?}
ISIN_P_PLUGINSALIASFILE=''
##

###
## $ZDOT/zshrc_local.d/021_MYAliases.additional.zsh
#MYP_ADDIALIASFILE=$ZDOT/zshrc_local.d/021_MYAliases.additional.zsh
# TMYP_ADDIALIASFILE="$(grep "alias $COMTOSEARCH=" "$MYP_ADDIALIASFILE" |  sed 's/^[ \t]*//' | grep -E '^alias')"
# ISIN_MYP_ADDIALIASFILE=''
###
#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
  cat<<__EOF__
  ${RED}
    usage:  [  ]

    Examples:
                                                 # .

  ${NC}
__EOF__
}
#----------------------------------------------------------------------------------------#
#                                       SCRIPT
#----------------------------------------------------------------------------------------#
#testparam
if [[ $# != 1 ]]; then
	echo "${RED}USAGE : whereisalias [ALIASNAME]${NC}"
	return 1
fi	

clear
    echo "${LINEE}"
	echo ""
	#######################################
    echo "===  Alias ${GREEN} $COMTOSEARCH ${NC} ==="
	#######################################
	echo ""
	echo "${LINEE}"
	echo ""

    ## $ZDOT/zshrc.d/020_aliases.main.zsh
	if [[ ${ALIASMAINLIST} == "" ]]; then
		echo "${RED}•${NC} Ne se trouve pas dans le fichier : ${RED}${P_MAINALIASFILE}${NC}"
	else
		echo "${GREEN}•${NC} Se trouve dans le fichier : ${GREEN}${P_MAINALIASFILE}${NC}"
		echo "${CYAN} ${ALIASMAINLIST} ${NC}"
		ISIN_P_MAINALIASFILE='YES'
	fi
	## $ZDOT/zshrc.d/021_aliases.universal.zsh
	if [[ ${ALIASUNILIST} == "" ]]; then
		echo "${RED}•${NC} Ne se trouve pas dans le fichier : ${RED}${P_UNIALIASFILE}${NC}"	
	else
		echo "${GREEN}•${NC} Se trouve dans le fichier : ${GREEN}${P_UNIALIASFILE}${NC}"
		echo "${YEL} ${ALIASUNILIST} ${NC}"
		ISIN_P_ADDIALIASFILE='YES'
	fi

    if [[ $IS_MAC ]]; then	
        ## $ZDOT/zshrc.d/022_aliases.darwin-specific.additional.zsh
        if [[ ${ALIASDARWINLIST} == "" ]]; then
            echo "${RED}•${NC} Ne se trouve pas dans le fichier : ${RED}${P_DARWALIASFILE}${NC}"	
        else
            echo "${GREEN}•${NC} Se trouve dans le fichier : ${GREEN}${P_DARWALIASFILE}${NC}"
            echo "${YEL} ${ALIASDARWINLIST} ${NC}"
            ISIN_P_DARWALIASFILE='YES'
        fi
    fi
    

    if [[ $IS_LINUX ]]; then 
        ## $ZDOT/zshrc.d/023_aliases.linux-specific.additional.zsh
        if [[ ${ALIASLINUXLIST} == "" ]]; then
            echo "${RED}•${NC} Ne se trouve pas dans le fichier : ${RED}${P_LINUXALIASFILE}${NC}"	
        else
            echo "${GREEN}•${NC} Se trouve dans le fichier : ${GREEN}${P_LINUXALIASFILE}${NC}"
            echo "${YEL} ${ALIASLINUXLIST} ${NC}"
            ISIN_P_LINUXALIASFILE='YES'
        fi
    fi

    ## $ZDOT/zshrc.d/local-functions/etc/grmlrc/grmlrc
	if [[ -f "${HOME}/.zsh/grmladdi" ]] && [[ $LOAD_GRML_ADDITION_FUNCTIONS == "YES" ]];then
        if [[ $ALIASGRMLLIST == "" ]]; then
            echo "${RED}•${NC} Ne se trouve pas dans le fichier : ${RED}$P_GRMLALIASFILE${NC}"
        else
            echo "${GREEN}•${NC} Se trouve dans le fichier : ${GREEN}$P_GRMLALIASFILE${NC}"
            echo "${GREEN}$ALIASGRMLLIST${NC}"
            ISIN_P_GRMLALIASFILE='YES'
        fi
    else
         echo "${RED}••${NC} GRML not currently actived.${NC}"
    fi

    ## $ZDOT/plugins
    if [[ $LOAD_PLUGINSEXTRA_FUNCTIONS == 'YES' && -f ${HOME}/.zsh/plugextraaddi ]]; then    
        if [[ $ALIASPLUGINSLIST == "" ]]; then
            echo "${RED}•${NC} Ne se trouve pas dans le dossier : ${RED}$P_PLUGINSALIASFILE${NC}"
        else
            echo "${GREEN}•${NC} Se trouve dans le dossier : ${GREEN}$P_PLUGINSALIASFILE${NC}"
            #echo "${GREEN} ${NC} Avec ce PATH :   ${GREEN}$ALIASPLUGINSPATH${NC}"
            echo "${MAGENTA}$ALIASPLUGINSLIST${NC}"
            ISIN_PLUGINSALIASFILE='YES'
        fi
     else
             echo "${RED}••${NC} Plugs-in extra are not currently actived.${NC}"

    fi
#####
#/!\#  
#####

	# ## $ZDOT/zshrc_local.d/021_MYAliases.additional.zsh
	# if [[ $TMYP_ADDIALIASFILE == "" ]]; then
	# 	echo "${RED}•${NC} Ne se trouve pas dans le fichier : ${RED}$MYP_ADDIALIASFILE${NC}"
	# 	echo ""
	# else

	# 	echo "${GREEN}•${NC} Se trouve dans le fichier : ${GREEN}$MYP_ADDIALIASFILE${NC}"
	# 	echo "$TMYP_ADDIALIASFILE"
	# 	ISIN_MYP_ADDIALIASFILE='YES'
	# fi
	echo ""
	echo "${LINEE}"	
return 0
