#! /usr/bin/env zsh -f

###########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2020. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# Z_Debug : Enable/disable debug mode on zsh

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 02/01/2019 :
# • Create this one

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
local VERSION FCT_NAME CONFILELIST

VERSION="0.0.1"
FCT_NAME='Z_Debug'

CONFILELIST=( $(find $P_ZDOTCONFDIR -maxdepth 1 -type f -name \*.zsh) )
 
#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
echo   ${RED}
cat<<__EOF__
    usage: Z_debug [ ON | OFF | XTRACEON | XTRACEOFF | help ]
__EOF__
echo ${NC} 
}


debugoff(){
# if [[ -f $P_ZDOTCONFDIR/001_ZeamonSH_wakeup.zsh.disabled ]] && [[ -f $P_ZDOTCONFDIR/001_ZeamonSH_wakeup.zsh.disabled ]]; then
#     echo ""
#     echo "${WN}ZaemonSH debug mode already off !${NC}"
#     echo ""
#     echo ""
#     sleep 2
# else
    #echo $CONFILELIST
 foreach conffile in $CONFILELIST; do
    # echo $conffile
     #echo "------"
      sed  -i -e 's/zshrc_load_status/#zshrc_load_status/g' $conffile
     # echo "------"
      sed  -i -e 's/zshrc_primary_load_status/#zshrc_primary_load_status/g' $conffile
     #echo "------"
 done
 mv $P_ZDOTCONFDIR/001_ZeamonSH_wakeup.zsh $P_ZDOTCONFDIR/001_ZeamonSH_wakeup.zsh.disabled
 mv $P_ZDOTCONFDIR/205_environment.login.message.zsh $P_ZDOTCONFDIR/205_environment.login.message.zsh.disabled
 rm -Rf $P_ZDOTCONFDIR/*.zsh-e
 Z_Restart
# fi
}
 
debugon(){
# if [[ -f $P_ZDOTCONFDIR/001_ZeamonSH_wakeup.zsh ]] && [[ -f $P_ZDOTCONFDIR/001_ZeamonSH_wakeup.zsh ]]; then
        # echo ""
        # echo "${WN}ZaemonSH debug mode already on !${NC}"
        # echo ""
        # echo ""
        # sleep 2
    # # else
 foreach conffile in $CONFILELIST; do
     #echo $conffile
     #echo "------"
      sed  -i -e 's/#zshrc_load_status/zshrc_load_status/g' $conffile
     # echo "------"
      sed  -i -e 's/#zshrc_primary_load_status/zshrc_primary_load_status/g' $conffile
     #echo "------"
 done
 rm -Rf $P_ZDOTCONFDIR/*.zsh-e
 mv $P_ZDOTCONFDIR/001_ZeamonSH_wakeup.zsh.disabled $P_ZDOTCONFDIR/001_ZeamonSH_wakeup.zsh
 mv $P_ZDOTCONFDIR/205_environment.login.message.zsh.disabled $P_ZDOTCONFDIR/205_environment.login.message.zsh    
 rm -Rf $P_ZDOTCONFDIR/*.zsh-e
 Z_Restart
# fi
}

xtraceon(){
    if [[ !  $(grep xtrace $P_ZDOTCONFDIR/016_environment.options.zsh | grep setopt)  ]]; then
        sed -i -e 's/setopt/setopt xtrace/g' $P_ZDOTCONFDIR/016_environment.options.zsh
        rm -Rf $P_ZDOTCONFDIR/*.zsh-e
        Z_Restart
    else
        echo "${WN}Xtrace already on !${NC}"
        echo ""
        echo ""
        sleep 2
    fi
}

xtraceoff(){
    if [[  $(grep xtrace $P_ZDOTCONFDIR/016_environment.options.zsh | grep setopt)  ]]; then
        sed  -i -e 's/setopt xtrace/setopt/g' $P_ZDOTCONFDIR/016_environment.options.zsh
         rm -Rf $P_ZDOTCONFDIR/*.zsh-e
        Z_Restart
    else
        echo "${WN}Xtrace already off !${NC}"
        echo ""
        echo ""
        sleep 2
    fi
}

banner
case $1 in
    help)
        help
        
        ;;
    OFF)
        debugoff
    ;;
    ON)
        debugon
    ;;
    XTRACEON)
        xtraceon 
    ;;
    XTRACEOFF)
        xtraceoff
     ;;
    *)
        help
    ;;
esac
