#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2020. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
#  Z_notes-tag-helper :

# -----------------------------------------------------------------------
# This script is really something that can be sourced into your shell, e.g.
#
#        source $HOME/.notes/notes-tag-helper
#
# Which gives you a wrapper around the `openmeta` program (from Google Code)
#      http://code.google.com/p/openmeta/
#
# Either have the openmeta executable on the command line, or set up the
# OPENMETA environment variable before sourcing this file.
# -----------------------------------------------------------------------

#
# The first argument is an "action" for the function which matches the
# action option to openmeta, specifically:
#
#   -t   to list the tags
#   -s   to set new tags
#   -a   to add additional tags to what a file already has
#
# If the function fails to find a file, it does nothing, otherwise, it displays
# the results.
#

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#
# 18/08/2019 :
#  • Dowload openmeta 

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 30/07/2017 :
#  • Create this one .
# 18/08/2019 :
#  • Unify script presentation. 


#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
 local VERSION FCT_NAME

 VERSION="0.0.1"
 FCT_NAME="$(echo $0)"

#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
   echo "${RED}"
   cat<<__EOF__
     usage:  Z_notes-tag-helper [  ]
         Z_notes-tag-helper   -t   to list the tags
         Z_notes-tag-helper   -s   to set new tags
         Z_notes-tag-helper   -a   to add additional tags to what a file already has
     Examples:
                                                  # .

__EOF__
 echo ${NC}
}

function tagit() {
    local ACTION="$1"
    shift 1

    local TAGS=""
    for ITEM in "$*"
    do
        # Let's check to see if we were given the file's title, but without
        # the .txt or .md extension, and let's determine if the file is in
        # the current directory or in the $NOTEDIR...
        if [ -f "$NOTEDIR/$ITEM.md" ]; then
            ITEM="$NOTEDIR/$ITEM.md"
        elif [ -f "$NOTEDIR/$ITEM.txt" ]; then
            ITEM="$NOTEDIR/$ITEM.txt"
        elif [ -f "$ITEM.md" ]; then
            ITEM="`pwd`/$ITEM.md"
        elif [ -f "$ITEM.txt" ]; then
            ITEM="`pwd`/$ITEM.txt"
        elif [ -f "$ITEM" ]; then
            ITEM="`pwd`/$ITEM"
            echo "Yippee..."
        elif [ -f "$NOTEDIR/$ITEM" ]; then
            ITEM="$NOTEDIR/$ITEM"
        fi

        # If we have the file, we can proceed, otherwise, we assume
        # the "item" is actually a tag name that we can add to our list.

        if [ -f "$ITEM" ]
        then
            ${OPENMETA:-openmeta} $ACTION $TAGS -p "$ITEM"
        else
            export TAGS="$TAGS $ITEM"
        fi
    done
alias tags="tagit -t"         # Lists the tag for a note
alias tag-clear="tagit -s"    # Removes all tags from a note
alias tag-add="tagit -a"      # Adds one or more tags
alias tag-set="tagit -s"      # Sets the tags to just these

}

#-------------------------------------------------------------------------------------------#
#                                              SCRIPT
#-------------------------------------------------------------------------------------------#
banner
[[ ! -e $1 ]] && help && return 0
#tagit
