#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2020. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# arduinoBuild  :
# Build Arduino sketch from CLI.

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#
# 01/08/2020 :
## Test if Arduino.app
## Test if binaries avr-gcc avr-objcopy avrdude
## Test if $1 and 
# To Finish.
#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 00/00/0000 :
#  • Create this one .

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
#######################
## COMMAND VARIABLES ##
#######################
local VERSION FCT_NAME

VERSION="0.0.1"
FCT_NAME="$(echo $0)"

local SKETCH MMCU PROGRAMMER SERIALPORT AVRDUDE_PATH AVRDUDE_CONF

#SKETCH="$(echo $1 | grep ".c$" | sed 's/\(.\)c/ /g')"
SKETCH="$(echo $1  | sed 's/\(.\)c//g' | tr '' '\n')"

MMCU="atmega328p"
PROGRAMMER="stk500v1"
SERIALPORT="/dev/$(ls /dev | grep cu.usbmodem | tr '' '\n')"


AVRDUDE_PATH="$HOME/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude"
AVRDUDE_CONF="$HOME/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"


#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
  echo "${RED}"
  cat<<__EOF__
    usage: $0 [  ]

    Examples:
                                                 # .


__EOF__
echo ${NC}
}

#----------------------------------------------------------------------------------------#
#                                       SCRIPT
#----------------------------------------------------------------------------------------#
emulate -L zsh
banner

if [ $1 ]; then
    # --First step :
    avr-gcc -mmcu=${MMCU} ${SKETCH}.c -o ${SKETCH}.o
    # --Second step :
    avr-objcopy -O ihex ${SKETCH}.o ${SKETCH}.hex
    # -- Last step :
    # ${AVRDUDE_PATH} -F -C ${AVRDUDE_CONF} -v -v -v -v -p ${MMCU} -c ${PROGRAMMER} -P $SERIALPORT -U flash:w:${SKETCH}.hex:i
else
    echo "USAGE :"
fi

### Modeline {{{
### vim:ft=zsh:foldmethod=marker
### vim:set ts=4:
### }}}
