#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2019. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# volume :
# Set volume from CLI.

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 04/01/2018 :
#  • Modify function presentation.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
#######################
## COMMAND VARIABLES ##
#######################
local VERSION FCT_NAME

VERSION="0.0.1"
FCT_NAME="$(echo $0)"

#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
    clear
    echo ${RED}
    cat<<__EOF__
    usage:  volume [ set | increase | decrease | up | down | mute | unmute | ismute ]

    Examples:
      volume              # get the volume level
      volume set 70       # set the volume to 70 %
      volume increase 5   # increase the volume by 5 (up to 5)
      volume decrease 10  # decrease the volume by 10 (down to 10)
      volume up           # increase the volume by 6.25
      volume down         # decrease the volume by 6.25
      volume mute         # set mute
      volume unmute       # unset mute
      volume ismute       # check the volume status
__EOF__

echo ${NC}
}

mute(){
    osascript -e "set volume output muted true"
    echo "Vol, Mute: true "
}

unmute(){
    osascript -e "set volume output muted false"
    echo "Vol, Mute: false"

}

is_mute(){
    VALUE=$(osascript -e 'output muted of (get volume settings)')
    echo "Vol, is mute: ${VALUE}"
}

set_vol(){
    osascript -e "set volume output volume $2"
    echo "Vol: $2"
}

adj_vol(){
    osascript -e "set volume output volume (get output volume of (get volume settings) $1)"
    get_vol
}

get_vol(){
    VALUE=$(osascript -e "output volume of (get volume settings)")
    echo "Vol: $VALUE"
} 
 
#-------------------------------------------------------------------------------------------#
#                                              SCRIPT
#-------------------------------------------------------------------------------------------#
banner
case $1 in
    # [0-9]*)
    #     set_vol $1
    #     ;;
    # +[0-9]*|-[0-9]*)
    #     adj_vol $1
    #     ;;
    set)
        set_vol $@
        ;;
    increase)
        adj_vol "+${1}"
       ;;
      decrease)
        adj_vol "-${1}"
       ;;
    up)
        adj_vol +6.25
        ;;
    up)
        adj_vol +6.25
        ;;        
    up)
        adj_vol +6.25
        ;;
    down)
        adj_vol -6.25
        ;;
    mute)
        mute
        ;;
    unmute)
        unmute
        ;;
    ismute)
        is_mute
        ;;
    help)
        help
        ;;
    *)
        get_vol
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
