.\"     Title: KWNARC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: User Manuals for kwnarc
.\"    Source: version 0.0.7
.\"
.TH "KWNARC" "8" "11/12/2013" "version 0.0.7" "User Manuals for kwnarc"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwnarc \- kwtools netfilter automatic rules configurator
.SH "SYNOPSIS"
.HP 7
\fBkwnarc\fR [\fBchains\fR | \fBconntrack\fR | \fBstart\fR | \fBstatus\fR | \fBstop\fR | \fBrestart\fR]
.SH "DESCRIPTION"
.PP
\fBkwnarc\fR
attempts to simplify the setup of a firewall (stateful packet filter) via the iptables tools\&.
\fBkwnarc\fR
is a
\fBZsh\fR
shellscript that generates (hopefully) sensible and secure rules for Netfilter based on a simple configuration file\&.
.\" line length increase to cope w/ tbl weirdness
.ll +(\n(LLu * 62u / 100u)
.TS
l.

T{
\fBkwnarc\fR Features (incomplete list):
T}
T{
Quick setup via a simple configuration file
T}
T{
Connection tracking (and fragmentation reassembly)
T}
T{
Customized logging
T}
T{
Probe detection (TCP and UDP)
T}
T{
Illegal TCP packet filtering
T}
T{
FIN, NULL, ACK scan detection
T}
T{
ICMP message filtering and rate limiting
T}
T{
SYN packet length checking
T}
T{
General rate limiting (to prevent DoS type attacks)
T}
T{
IP/network based TCP connection rate limiting
T}
T{
SYN flood protection
T}
T{
Smurf attack protection
T}
T{
Spoofed IP address filtering
T}
T{
DMZ support
T}
T{
Port forwarding support
T}
.TE
.\" line length decrease back to previous value
.ll -(\n(LLu * 62u / 100u)
.sp
.SH "OPTIONS"
.PP
\fBchains\fR
.RS 4
Displaying current chains\&.
.RE
.PP
\fBconntrack\fR
.RS 4
Displaying current connection tracking info\&.
.RE
.PP
\fBstart\fR
.RS 4
Starting iptables and create all chains\&.
.RE
.PP
\fBstatus\fR
.RS 4
Displaying active rules\&.
.RE
.PP
\fBstop\fR
.RS 4
Stopping iptables and deleting all chains\&.
.RE
.PP
\fBrestart\fR
.RS 4
Stopping and starting iptables new\&.
.RE
.SH "FILES"
.PP
\fI/etc/kwtools/kwnarc\&.conf\fR
.RS 4
The main configuration file\&. See
\fBkwnarc.conf\fR(5)
for further details\&.
.RE
.PP
\fI/etc/kwtools/kwnarc\-custom\&.conf\fR
.RS 4
Configuration file for custom rules\&. See in
\fI/usr/share/doc/kwtools\-net\-narc/examles\fR
for a example\&.
.RE
.PP
\fI/etc/kwtools/kwnarc\-forward\&.conf\fR
.RS 4
Configuration file for port forwarding\&. See in
\fI/usr/share/doc/kwtools\-net\-narc/examles\fR
for a example\&.
.RE
.SH "SEE ALSO"
.PP
\fBiptables\fR(8),
\fBkwnarcconf\fR(8),
\fBkwnarc.conf\fR(5)
.SH "AUTHOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Wrote the manpage in DocBook XML for the Debian distribution\&.
.SH "COPYRIGHT"
Copyright \(co 2006-2013 Kai Wilke
.br
