#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2019. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
#  dns :
#  Flush dns cache on darwin system.

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#
# 13/01/2018 :
#  • Integrated this script :

####################################################################################################
#
# ABOUT THIS PROGRAM
#
# NAME
#   setDNSServers.sh -- Set a DNS server for a specified network interface
#
# SYNOPSIS
#   sudo setDNSServers.sh
#   sudo setDNSServers.sh <mountPoint> <computerName> <currentUsername> <networkInterface>
#                           <dnsServer> 
#
#   If the $networkInterface parameter is specified (parameter 4), this is the Netowrk Interface for
#   which DNS server that will be set.  The expected values for the $networkInterface parameter can
#   be found by running the command:
#
#       networksetup -listallnetworkservices
#
#   If the $dnsServer parameter is specified (parameter 5), this is the DNS server that will be set.
#
#   If no parameter is specified for parameters 4 and 5, the hardcoded value in the script will be used.
#
# DESCRIPTION
#   This script will set a DNS Server in the network settings for whichever network interface has
#   been specified.
#
####################################################################################################
#
# DEFINE VARIABLES & READ IN PARAMETERS
#
####################################################################################################
# HARDCODED VALUES ARE SET HERE
# networkInterface=""
# dnsServer=""
#
#
# # CHECK TO SEE IF A VALUE WAS PASSED IN PARAMETER 4 AND, IF SO, ASSIGN TO "networkInterface"
# if [ "$4" != "" ] && [ "$networkInterface" == "" ];then
#     networkInterface=$4
# fi
#
# # CHECK TO SEE IF A VALUE WAS PASSED IN PARAMETER 5 AND, IF SO, ASSIGN TO "dnsServer"
# if [ "$5" != "" ] && [ "$dnsServer" == "" ];then
#     dnsServer=$5
# fi
# if [ "$networkInterface" == "" ]; then
#     echo "Error:  No network interface has been specified."
#     exit 1
# fi
#
# if [ "$dnsServer" == "" ]; then
#     echo "Error:  No DNS server has been specified."
#     exit 1
# fi
#
# OS=`/usr/bin/defaults read /System/Library/CoreServices/SystemVersion ProductVersion | awk '{print substr($1,1,4)}'`
#
# if [[ "$OS" < "10.5" ]]; then
#     echo "Setting DNS Server for OS $OS..."
#     /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Support/networksetup -setdnsservers "$networkInterface" "$dnsServer"
# else
#     echo "Setting DNS Server for OS $OS..."
#     /usr/sbin/networksetup -setdnsservers "$networkInterface" "$dnsServer"
# fi
#####################################################################################################
#
#  2020-08-03 :
#  • Make a completion.
#  • To Finish

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 04/01/2018 :
#  • Modify function presentation.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
#######################
## COMMAND VARIABLES ##
#######################
local VERSION FCT_NAME

VERSION="0.0.1"
FCT_NAME="$(echo $0)"

#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
    cat<<__EOF__
    ${RED}
    usage:  dns [ flush | show | help ]

    Examples:
      dns flush       # flushes local DNS
    ${NC}
__EOF__
}

flushdns(){
    VERSION=$(sw_vers -productVersion)
    echo "Flushing dns..."
    if echo $VERSION | grep -E '^10\.10(\.[0-3])?$' >/dev/null 2>&1; then
        sudo discoveryutil mdnsflushcache
    elif echo $VERSION | grep -E '^10\.6(\.[0-8])?$' >/dev/null 2>&1; then
        sudo dscacheutil -flushcache
    else
        sudo killall -HUP mDNSResponder
    fi
}

SystemConfDns(){
  # show current DNS configuration
  scutil --dns
}

#-------------------------------------------------------------------------------------------#
#                                              SCRIPT
#-------------------------------------------------------------------------------------------#
banner
case $1 in
    help)
        help
        ;;
    flush)
        shift
        flushdns
        ;;
    show)
        shift
        SystemConfDns
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
