#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2020. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# Z_Configure_zaemonsh_templates v0.0.2 :
# This is a wrapper script that will attempt to call the correct darwin installation function.
# small one (Z_Configure_zaemonsh_templates_asgui) or large one (Z_Configure_zaemonsh_templates_pashua).

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 28/09/2017 :
 # • Unify script presentation.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
## Local variables.
local VERSION timeout dialogue_text button_items option_array

VERSION="v0.0.2"

## local functions.
local Z_Osa_display_dialog
#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#

#  function Z_Osa_display_dialog takes up to three arguments (button item options)
#  supplied after invoking the function.
Z_Osa_display_dialog () {
#  Display times out according to the variable $timeout in seconds (defaults to 15 sec).

    if [[ -z $timeout ]];then
        timeout='15'
    fi

# The variable $dialogue_text is an array that contains the text displayed in the window.
    if [[ -z $dialogue_text ]];then
        dialogue_text=( Choose a button: )
    fi
    
    
    if (( $# > 3 || $# == 0 )); then
        print "Usage:  list up to 3 button names, with the last as default choice (eg: No 42 OK )"
        return 11
    fi
    # Thanks to Gary Kerbaugh for the next five lines
    button_items="" 
    for argument in "$@"; do 
       button_items=${button_items}\"${argument}'", ' 
    done 
    button_items=${button_items%, } 
  
    if (( $# == 3 ));then
        def_but="$3"
    elif (( $# == 2 ));then
        def_but="$2"
    else
        def_but="$1"    
    fi
    
osascript << eof
    tell app "Finder"
    activate
    set r to display dialog "$dialogue_text" buttons { $button_items } with icon caution giving up after $timeout default button "$def_but"
    set ButtonChoice to button returned of r
    end tell
eof
}

#-------------------------------------------------------------------------------------------#
#                                                SCRIPT
#-------------------------------------------------------------------------------------------#
timeout='45'
dialogue_text=( To configure the zsh templates, you can choose to use a series of
    small dialog boxes like this one \(better for smaller displays\) or a single
    larger configuration pane \(more suited to larger displays\). You will be asked
    a series of questions, and can choose to change things or leave them as they are.
    You can undo any changes later by issuing the command:  Z_Configure_zaemonsh_templates )

option_array=($( Z_Osa_display_dialog  "do this later" "small dialog boxes"  "one large pane" ))

if [[ "$option_array" ==  "one large pane" ]]; then
    autoload -U Z_Configure_zaemonsh_templates_pashua
    Z_Configure_zaemonsh_templates_pashua 
elif [[ "$option_array" ==  "small dialog boxes" ]]; then
    autoload -U Z_Configure_zaemonsh_templates_asgui
    Z_Configure_zaemonsh_templates_asgui 
else  
    # Do nothing
    print "Issue the command \e[1m Z_Configure_zaemonsh_templates \e[0m to restart this process."
fi
return 0

