.\"     Title: KWCAMERARC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: 
.\"    Source: Version 0.0.6
.\"
.TH "KWCAMERARC" "5" "11/15/2013" "Version 0.0.6" "Benutzer Anleitung"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwcamerarc \- Konfigurationsdatei f\(:ur kwcamera.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwcamera\fR
wird die Datei
\fI~/\&.kwtools/kwcamerarc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwcamera\fR
ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBIMAGE_DIR\fR
.RS 4
Geben Sie hier das Grundverzeichnis an, unter dem Ihre Bilder gespeichert werden sollen\&.
.RE
.PP
\fBCAMERA_PORT\fR
.RS 4
Geben Sie hier den Port ein an dem standardm\(:assig Ihre Kamera angeschlossen ist\&. Mit
\fBgphoto(2)\fR
\fB\-\-list\-ports\fR
k\(:onnen Sie sich alle, vom OS, unterst\(:utzten Ports anschauen\&. Mit
\fBgphoto(2)\fR
\fB\-\-auto\-detect\fR
k\(:onnen Sie sich alle angeschlossenen Kameras + Ports anschauen\&.
.RE
.PP
\fBCAMERA_MODELL\fR
.RS 4
Geben Sie hier Ihr Kamera Modell ein\&. Mit
\fBgphoto(2)\fR
\fB\-\-list\-cameras\fR
k\(:onnen Sie sich alle unterst\(:utzten Kamera Modelle ansehen\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwcamerarc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwcamera\fR
F\(:ur weitere Details siehe
\fBkwcamera\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBgphoto(2)\fR(1),
\fBkwcamera\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
