.\"     Title: KWECRYPTFSRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: 
.\"    Source: Version 0.0.4
.\"
.TH "KWECRYPTFSRC" "5" "11/15/2013" "Version 0.0.4" "Benutzer Anleitung"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwecryptfsrc \- Konfigurationsdatei f\(:ur kwecryptfs.
.SH "BESCHREIBUNG"
.PP
Dies ist die Standard Konfigurationsdatei vom Script
\fBkwecryptfs\fR\&. Diese Werte werden beim Erstellen von verschl\(:usselten Verzeichnissen angeboten\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBCIPHER\fR
.RS 4
W\(:ahlen Sie einen Chiffrierungstyp aus (\fBaes, blowfish, des3_ede, twofish, cast5, cast6, arc4\fR)\&. Standard ist
\(lq\fBaes\fR\(rq\&.
.RE
.PP
\fBKEY_SIZE\fR
.RS 4
Auswahl der Schl\(:usselgr\(:osse (\fB16, 24, 32\fR)\&. Standard ist
\fB16\fR\&.
.RE
.PP
\fBKEY_TYP\fR
.RS 4
Geben Sie den Schl\(:usseltyp an (\fBgpg, openssl, passphrase, pkcs11\-helper, tspi\fR) ein\&. Die unterst\(:utzten Schl\(:usseltypen liegen normalerweise unter
\fI/usr/lib*/ecryptfs/\fR\&. Standard ist
\fBpassphrase\fR\&. Dazu muss man noch eine Schl\(:ussel Option, wie eine Schl\(:usseldatei mit angeben\&. Beispiele:
.sp
\fBKEY_TYPE\fR=\fBkeytype\fR:\fBkey_option\fR=\fBoption\fR
.sp
Einige der folgenden Werte kann man kombinieren\&. Z\&. B\&.
\%\fBKEY_TYPE\fR=\fB\%openssl:openssl_keyfile\fR=\fI\%/path/to/openssl_private_RSA_file\fR:\fB\%openssl_passwd_file\fR=\fI\%/path/to/openssl_password_file\fR
.sp
\fBKEY_TYPE\fR=\fBgpg\fR
\- Hier ist noch nichts
.sp
\fBKEY_TYPE\fR=\fBopenssl\fR:\fBopenssl_passwd\fR=\fIpassphrase\fR
.sp
\fBKEY_TYPE\fR=\fBopenssl\fR:\fBopenssl_passwd_file\fR=\fI/path/to/openssl_password_file\fR
.sp
Auswahl einer Datei die die/den Schl\(:ussel enth\(:alt\&. Die Syntax der Datei ist
\fBopenssl_passwd\fR=\fIpassphrase\fR\&. Bei dieser Auswahl k\(:onnen Sie zus\(:atzlich eine Openssl private RSA SSL Schl\(:usseldatei ausw\(:ahlen oder eine Passphrase mit eingeben\&.
.sp
\fBKEY_TYPE\fR=\fBopenssl\fR:\fBopenssl_keyfile\fR=\fI/path/to/openssl_private_RSA_file\fR
.sp
Auswahl einer Openssl private RSA SSL Schl\(:ussel Datei\&. Bei dieser Auswahl k\(:onnen Sie zus\(:atzlich eine Openssl Schl\(:ussel Datei ausw\(:ahlen oder eine Passphrase mit eingeben\&.
.sp
\fBKEY_TYPE\fR=\fBpassphrase\fR:\fBpassphrase_passwd\fR=\fIpassphrase\fR
.sp
\fBKEY_TYPE\fR=\fBpassphrase\fR:\fBpassphrase_passwd_file\fR=\fI/path/to/password_file\fR
.sp
Die Syntax der Datei ist
\fBpasswd\fR=\fIpassphrase\fR\&.
.sp
\fBKEY_TYPE\fR=\fBpassphrase\fR:\fBpassphrase_salt\fR=16 digit hex Wert\&.
.sp
\fBKEY_TYPE\fR=\fBpkcs11\-helper\fR
\- Hier ist noch nichts
.sp
\fBKEY_TYPE\fR=\fBtspi\fR
\- Hier ist noch nichts
.sp
Siehe
\fBecryptfs\fR(7)\&.
.RE
.PP
\fBMOUNT_PATH\fR
.RS 4
Mountverzeichnis ausw\(:ahlen\&. Dieses Verzeichnis muss schon vorher existieren und sollte in der Datei
\fI/etc/fstab\fR
konfiguriert sein\&. Dieses dient zum einbinden von externen Laufwerken, die die externe Schl\(:usseldatei enthalten\&.
.RE
.PP
\fBNOAUTO\fR
.RS 4
Soll das Laufwerk nicht beim starten des Rechners erstellt werden, sondern manuell (\fByes/no\fR)? Also nicht automatisch\&.
.RE
.PP
\fBNO_SIG_CACHE\fR
.RS 4
Soll die gemountete Schl\(:ussel Signatur mit dem Wert in
\fI~/\&.ecryptfs/sig\-cache\&.txt\fR
verglichen werden (\fByes/no\fR)?
\(lq\fBno\fR\(rq
ist gut f\(:ur nicht interactive Setup Scripts\&.
.RE
.PP
\fBPASSTHROUGH\fR
.RS 4
Sollen nicht verschl\(:usselte Dateien ins verschl\(:usselte Dateisystem durch gereicht werden (\fByes/no\fR)?
\(lq\fByes\fR\(rq
ist gut um auch unverschl\(:usselte Dateien zu bearbeiten\&.
.RE
.PP
\fBVERSION\fR
.RS 4
Soll die Version der verschl\(:usselten Dateien angezeigt werden (\fByes/no\fR)?
\(lq\fByes\fR\(rq
ist gut f\(:ur Backup Tools die erweiterte Attribute des Dateisystems unterst\(:utzen, wie
\fIext2/3\fR\&.
.RE
.PP
\fBXATTR\fR
.RS 4
Sollen die Metadaten der verschl\(:usselten Dateien in den erweiterten Attributen des Dateisystems gespeichert werden (\fByes/no\fR)? Dateisysteme wie
\fIext2/3/4\fR
unterst\(:utzen dies zum Beispiel\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwecryptfsrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwecryptfs\fR
F\(:ur weitere Details siehe
\fBkwecryptfs\fR(8)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBecryptfs\fR(7),
\fBkwecryptfs\fR(8),
\fBmount\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2009-2013 Kai Wilke
.br
