.\"     Title: KWLOSETUPRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: 
.\"    Source: Version 0.1.12
.\"
.TH "KWLOSETUPRC" "5" "11/15/2013" "Version 0.1.12" "Benutzer Anleitung"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwlosetuprc \- Konfigurationsdatei f\(:ur kwlosetup.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwlosetup\fR
wird die Datei
\fI~/\&.kwtools/kwlosetuprc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwlosetup\fR
ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBBLOCK_SIZE\fR
.RS 4
Geben sie hier die Blockgr\(:osse an, die Ihr verschl\(:usselter Container haben soll\&. Diese muss ein vielfaches von
\fB512\fR
sein\&.
.RE
.PP
\fBCONTAINER\fR
.RS 4
Geben Sie hier den Namen des Containers mit vollem Pfad an\&.
.RE
.PP
\fBCONT_SIZE\fR
.RS 4
Geben Sie hier die Gr\(:osse des verschl\(:usselten Containers ein\&. F\(:ur die Masseinheit k\(:onnen Sie folgende Zeichen benutzen [\fIkKmMtTpPeEzZ\fR],
\fB1M\fR=\fI1MByte\fR\&.
.RE
.PP
\fBENCRYPT\fR
.RS 4
Verschl\(:usselungsverfahren (AES*, twofish*, \&.\&.\&.)\&. Lesen Sie dazu (\fBlosetup\fR(8))\&.
.RE
.PP
\fBMULTI_KEY\fR
.RS 4
Multi_Key aktivieren (\fByes/no\fR)? Bei
\fBMULTI_KEY\fR=\fIyes\fR
werden die Passw\(:orter aus einer verschl\(:usselten gpg\-Datei gelesen\&. Bei
\fBMULTI_KEY\fR=\fIno\fR
muss eine mindestens 20 Zeichen lange Passphrase \(:ubergeben werden\&.
.RE
.PP
\fBMOUNT_PATH\fR
.RS 4
Verzeichnis welches eingebunden werden muss, wenn der Schl\(:ussel z\&.B\&. auf einem externen Medium liegt, wie einem USBstick\&.
.RE
.PP
\fBKEY_FILE_PATH\fR
.RS 4
Verzeichnis, in dem die verschl\(:usselte Schl\(:usseldatei liegt\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwlosetuprc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwlosetup\fR\&. F\(:ur weitere Details siehe
\fBkwlosetup\fR(8)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwlosetup\fR(8),
\fBlosetup\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
