.\"     Title: KWPLANERRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: 
.\"    Source: Version 0.0.6
.\"
.TH "KWPLANERRC" "5" "11/15/2013" "Version 0.0.6" "Benutzer Anleitung"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwplanerrc \- Konfigurationsdatei f\(:ur kwplaner.
.SH "BESCHREIBUNG"
.PP
Beim Start der Scripte
\fBkwtermin\fR
und
\fBkwplaner\fR
wird die Datei
\fI~/\&.kwtools/kwplanerrc\fR
eingelesen\&. Sie beinhaltet Variablen die von den Programmen
\fBgcal\fR,
\fBcalendar\fR
und den Scripten
\fBcreate\&.cal\&.pl\fR,
\fBkwholiday\fR,
\fBkwtermin\fR,
\fBkwtermin_cron\fR
und
\fBkwtex\-cal\fR
ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBMAIL_ADR\fR
.RS 4
Ihre Mailadresse, ist Sie nicht belegt wird
\fIUSER@localhost\fR
genommen\&.
.RE
.PP
\fBCAL_VIEW\fR
.RS 4
Kalenderansicht,
\fBt\(:aglich\fR,
\fBw\(:ochentlich\fR,
\fBmonatlich\fR
und
\fBj\(:ahrlich\fR\&. Ist die Variable leer wird
\fBw\(:ochentlich\fR
genutzt\&.
\fBw\(:ochentlich\fR
=
\fI1 weeks\fR
(\fBinfo date\fR)\&.
.RE
.PP
\fBFEIERTAG_DIR\fR
.RS 4
Geben Sie hier das Grundverzeichnis der calendar Dateien an\&. Bei Debian ist dies das Verzeichnis
\fI/usr/share/calendar\fR\&.
.RE
.PP
\fBBLAND\fR
.RS 4
Geben Sie hier das Land/Bundesland ein (\fBDeutschland/Hamburg\fR=\fIDE_HA\fR)\&. Siehe
\fBgcal\fR
\fB\-\-usage=cc\fR\&.
.RE
.PP
\fBCAL\fR
.RS 4
Geben Sie hier die Calendar Dateien mit vollem Pfad an in denen nach Feiertagen gesucht werden soll, getrennt durch ein Leerzeichen\&. Diese Dateien liegen bei Debian im Pfad
\fI/usr/share/calendar\fR\&.
.RE
.PP
\fBPLAN_HOST\fR
.RS 4
Rechnername oder IP\-Adresse auf dem das Program kwplaner l\(:auft\&. Zur Zeit geht nur der lokale Rechner\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwplanerrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwplaner\fR
und anderen Scripts\&. F\(:ur weitere Details siehe
\fBkwplaner\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcalendar\fR(1),
\fBgcal\fR(1),
\fBkwholiday\fR(1),
\fBkwplaner\fR(1),
\fBkwtermin\fR(1),
\fBkwtermin_cron\fR(1),
\fBkwtex-cal\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
