.\"     Title: KWPWSAFERC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: 
.\"    Source: Version 0.0.9
.\"
.TH "KWPWSAFERC" "5" "11/15/2013" "Version 0.0.9" "Benutzer Anleitung"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwpwsaferc \- Konfigurationsdatei f\(:ur kwpwsafe.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwpwsafe\fR
wird die Datei
\fI~/\&.kwtools/kwpwsaferc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwpwsafe\fR
benutzt werden k\(:onnen, zum \(:offnen einer Standard Datenbank oder zum generieren von Passw\(:ortern\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBDEFAULT_PWSAFE_FILE\fR
.RS 4
Beinhaltet die Datenbank die standardm\(:assig ge\(:offnet werden soll\&.
.RE
.PP
\fBPASSWD_LENGTH\fR
.RS 4
Passwortl\(:ange f\(:ur zu generierende Passw\(:orter\&. Standard ist eine L\(:ange von 8 Zeichen\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwpwsaferc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwpwsafe\fR\&. F\(:ur weitere Details siehe
\fBkwpwsafe\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwpwsafe\fR(1),
\fBpwsafe\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2009-2013 Kai Wilke
.br
