.\"     Title: KWRIPRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.75.0 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual:
.\"    Source: Version 0.0.9
.\"  Language: English
.\"
.TH "KWRIPRC" "5" "11/15/2013" "Version 0.0.9" "Benutzer Anleitung"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwriprc \- Konfigurationsdatei f\(:ur kwrip\&.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwrip\fR
wird die Datei
\fI~/\&.kwtools/kwriprc\fR
eingelesen\&. Diese werden haupts\(:achlich von den Programmen
\fBcd\-discid\fR,
\fBcddbcmd\fR,
\fBcdparanoia\fR
und
\fBvcdxrip\fR
ben\(:otigt\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBAUDIO_OPTIONS\fR
.RS 4
Geben Sie hier die Optionen f\(:ur das Audio rippen ein\&. Es wird
\fBcdparanoia\fR
benutzt (man 1 cdparanoia)\&. Standard ist
\(lq\fB\-w\fR\(rq\&. Geben Sie nicht das Leselaufwerk und
\(lq\fB\-B\fR\(rq
in den
\fBAUDIO_OPTIONS\fR
mit an\&. Das Laufwerk wird selbstst\(:andig angeh\(:angt, solange
\fBREAD_DEVICE\fR
konfiguriert ist\&. Die Option
\(lq\fB\-B\fR\(rq
wird an das Laufwerk angeh\(:angt, falls nicht gleichzeitig auch encodiert werden soll\&. Die Option
\(lq\fB\-B\fR\(rq
steht f\(:ur Batch Mode und speichert die Sounddateien im Format
track#\&.cdda\&.*\&. Wobei
\(lq#\(rq
die jeweilige Tracknummer ist\&.
.RE
.PP
\fBAUDIO_MOUNT_PATH\fR
.RS 4
Geben Sie hier das Mountverzeichnis ein\&. Dieses Verzeichnis muss in der Datei
\fI/etc/fstab\fR
konfiguriert sein\&. Dies kann man nutzen falls das Audio Verzeichnis nicht standardm\(:assig ins System eingebunden ist\&.
.RE
.PP
\fBAUDIO_DIR\fR
.RS 4
Geben Sie hier das Standard Audioverzeichnis ein\&. Sie brauchen keine Ordner f\(:ur Artist und Album vergeben, diese werden \(:uber die CDDB Datenbank Abfrage erledigt\&. Wird kein Eintrag in der Datenbank gefunden wird alles im ausgw\(:ahltem Verzeichnis
\fBunknown/unknown\fR
gespeichert\&. Es kommt eine Information dar\(:uber\&.
.RE
.PP
\fBCDDB\fR
.RS 4
Soll ein CD Datenbank Server abgefragt werden (\fByes/no\fR)?
.RE
.PP
\fBCDDB_SERVER\fR
.RS 4
Geben Sie hier einen CD Datenbank Server ein\&. Standard ist
\fBfreedb\&.freedb\&.org\fR\&.
.RE
.PP
\fBREAD_DEVICE\fR
.RS 4
Auswahl eines der vorhandenen
CD/DVD
Laufwerke\&.
.RE
.PP
\fBEJECT\fR
.RS 4
Auswahl ob die
CD/DVD
nach dem rippen ausgeworfen werden soll (\fByes/no\fR)?\&.
.RE
.PP
\fBPROXY\fR
.RS 4
Proxy Einstellungen f\(:ur die CD Datenbank Abfrage\&. Es k\(:onnen der
\fBRechnername:Port\fR
oder
\fBIP\-Adresse:Port\fR
eingegeben werden\&. Ist optional, falls sie die globalen Variablen
\fBhttp_proxy\fR
und/oder
\fBftp_proxy\fR
konfiguriert haben, z\&. B\&. mit
\fBkwproxy\fR
(Paket
kwtools\-net)\&.
.RE
.PP
\fBENCODE\fR
.RS 4
Sollen die Dateien gleich encodiert werden (\fByes/no\fR)?
.RE
.PP
\fBFM_PROG\fR
.RS 4
Auswahl der vorhandenen Encodierungsprogramme\&. Z\&. Z\&. werden nur
\fBlame\fR
und
\fBoggenc\fR
unterst\(:utzt\&.
.RE
.PP
\fBLAME_ENC_OPT\fR
.RS 4
Geben Sie hier die Optionen zur Encodierung mit
\fBlame\fR
ein\&.
.RE
.PP
\fBOGG_ENC_OPT\fR
.RS 4
Geben Sie hier die Optionen zur Encodierung mit
\fBoggenc\fR
ein\&.
.RE
.PP
\fBVIDEO_MOUNT_PATH\fR
.RS 4
Geben Sie hier das Mountverzeichnis ein\&. Dieses Verzeichnis muss in der Datei
\fI/etc/fstab\fR
konfiguriert sein\&. Dies kann man nutzen falls das Video Verzeichnis nicht standardm\(:assig ins System eingebunden ist\&.
.RE
.PP
\fBVIDEO_DIR\fR
.RS 4
Geben Sie hier das Standard Videoverzeichnis an, in das Ihre Filme gerippt werden sollen\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwriprc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwrip\fR
F\(:ur weitere Details siehe
\fBkwrip\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcddbcmd\fR(1),
\fBcd_discid\fR(1),
\fBcdparanoia\fR(1),
\fBkwrip\fR(1),
\fBlame\fR(1),
\fBoggenc\fR(1),
\fBvcdxrip\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
CopyrightCopyright \(co 2002-2013 Kai Wilke
.br
