.\"     Title: KWRSYNCRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 05/04/2015
.\"    Manual: Benutzer Anleitung
.\"    Source: Version 1.0.2
.\"  Language: English
.\"
.TH "KWRSYNCRC" "5" "05/04/2015" "Version 1.0.2" "Benutzer Anleitung"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwrsyncrc \- Konfigurationsdatei f\(:ur kwrsync\&.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwrsync\fR
wird die Datei
\fI~/\&.kwtools/kwrsyncrc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwrsync\fR
ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBR_HOST\fR
.RS 4
Geben Sie hier die Zielrechner an, mit denen das Home Verzeichnis synchronisiert werden soll\&. Dies k\(:onnen Rechnernamen oder IP\-Adressen sein\&.
.RE
.PP
\fBRSYNC_RSH\fR
.RS 4
Welche Shell soll f\(:ur \(:Ubertragung genutzt werden\&. Zur Auswahl stehen
\fBssh\fR
und
\fBrsh\fR, falls sie installiert sind\&. Die
\fBssh\fR
besitzt eine Kompression und \(:ubertr\(:agt alles verschl\(:usselt\&.
.RE
.PP
\fBBW_LIMIT\fR
.RS 4
Hier k\(:onnen Sie die Bandbreite der \(:Ubertragung limitieren (z\&.B
\fB256\fR
=
\fB256KB/s\fR)\&. Standard ist keine Limitierung\&.
.RE
.PP
\fBHOME_SYNC_CRON\fR
.RS 4
Soll die Synchronisation des Home Verzeichnisses per cron durchgef\(:uhrt werden (\fIyes\fR/\fIno\fR)?
.RE
.PP
.RS 4
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwrsyncrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwrsync\fR
F\(:ur weitere Details siehe
\fBkwrsync\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwrsync\fR(1),
\fBkwrsync_cron\fR(1),
\fBrsync\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2002-2013 Kai Wilke
.br
