.\"     Title: KWSND2SNDFMRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: Benutzer Anleitung
.\"    Source: Version 0.0.9
.\"
.TH "KWSND2SNDFMRC" "5" "11/15/2013" "Version 0.0.9" "Benutzer Anleitung"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwsnd2sndfmrc \- Konfigurationsdatei f\(:ur kwsnd2sndfm.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwsnd2sndfm\fR
wird die Datei
\fI~/\&.kwtools/kwsnd2sndfmrc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwsnd2sndfm\fR
ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBSND_DIR\fR
.RS 4
Geben Sie hier das Verzeichnis an in welchem die Sound Dateien liegen\&.
.RE
.PP
\fBMOUNT_PATH\fR
.RS 4
Wie heisst das/die Verzeichnis/Partition, welches eingebunden werden muss\&. Diese(s) muss in der Datei
\fI/etc/fstab\fR
stehen\&.
.RE
.PP
\fBLAME_DEC_OPT\fR
.RS 4
Geben Sie hier die Optionen zum decodieren f\(:ur
\fBlame\fR
ein\&. Standard ist die Option
\(lq\fB\-\-decode\fR\(rq\&.
.RE
.PP
\fBLAME_ENC_OPT\fR
.RS 4
Geben Sie hier die Optionen zum encodieren f\(:ur
\fBlame\fR
ein\&. Standard sind die Optionen
\(lq\fB\-\-r3mix \-b112\fR\(rq\&.
.RE
.PP
\fBOGG_DEC_OPT\fR
.RS 4
Geben Sie hier die Optionen zum decodieren f\(:ur
\fBoggdec\fR
ein\&. Standard sind die Optionen
\(lq\fB\-R 1 \-e 1 \-b 16\fR\(rq\&.
.RE
.PP
\fBOGG_ENC_OPT\fR
.RS 4
Geben Sie hier die Optionen zum encodieren f\(:ur
\fBoggenc\fR
ein\&. Standard sind die Optionen
\(lq\fB\-b 128 \-o\fR\(rq\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwsnd2sndfmrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwsnd2sndfm\fR
F\(:ur weitere Details siehe
\fBkwsnd2sndfm\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwsnd2sndfm\fR(1),
\fBlame\fR(1),
\fBoggdec\fR(1),
\fBoggenc\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
