.\"     Title: KWUSERRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 11/16/2013
.\"    Manual: Benutzer Anleitung
.\"    Source: Version 1.0.3
.\"  Language: English
.\"
.TH "KWUSERRC" "5" "11/16/2013" "Version 1.0.3" "Benutzer Anleitung"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwuserrc \- Konfigurationsdatei f\(:ur kwuser\&.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwuser\fR
wird die Datei
\fI/root/\&.kwtools/kwuserrc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwuser\fR
benutzt werden k\(:onnen, zum erstellen von neuen Benutzern\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBKW_GROUP\fR
.RS 4
Hauptgruppe des zu erstellenden Benutzers bestimmen (Bsp\&.:
\fIusers\fR)\&.
.RE
.PP
\fBKW_GROUPS\fR
.RS 4
Gruppen einstellen zu welchen der zu erstellende Benutzer geh\(:oren soll\&. Wird keine Gruppe eingestellt kommt die Gruppe
\(lq\fIusers\fR\(rq
zum Zuge (Standard)\&.
.RE
.PP
\fBShell\fR
.RS 4
Eine der installierten Shells, als Standard, zum erstellen von Benutzer Accounts ausw\(:ahlen\&.
.RE
.PP
\fBPasswortl\(:ange\fR
.RS 4
Eingabe einer Passwortl\(:ange die beim generieren eines Passwortes benutzt werden soll\&. Wird nichts angegeben wird eine L\(:ange von 8 Zeichen benutzt\&.
.RE
.PP
\fBErstlogin\fR
.RS 4
Zu Einstellungen (Passwortaenderung) beim 1\&. Login auffordern (\fIyes\fR/\fIno\fR)? Standard ist
\(lq\fIyes\fR\(rq\&.
.sp
Notiz: Ben\(:otigt das Paket
\(lq\fBkwtools\-sys\-kwpasswd\fR\(rq, ausser Sie benutzen die Sourcen\&.
.PP
Quota Einstellungen zum anlegen von Benutzern\&. Quota bedeutet Plattenplatzbeschr\(:ankung\&. Quota wird nur angelegt wenn das Home Verzeichnis des Benutzers auch auf einer eigenen Partition mit
\fB\(lqQuota\(rq\fR
Unterst\(:utzung liegt (Bsp\&.:
\fI/home/user\fR
=
\fI/home\fR
\fBQuota\fR
Laufwerk)\&.
.SH ""
.PP
\fBBH_LIMIT\fR
.RS 4
Gr\(:osse des Block Hardlimits\&. Als Masseinheit stehen kib,Kib,KiB,mib,Mib,MiB,gib,Gib,GiB,\&.\&.\&.\&. zur Verf\(:ugung\&.
.RE
.PP
\fBBS_LIMIT\fR
.RS 4
Gr\(:osse des Block Softlimits\&. Siehe Block_Hardlimit\&.
.RE
.SH "DATEI"
.PP
\fI/root/\&.kwtools/kwuserrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwuser\fR\&. F\(:ur weitere Details siehe
\fBkwuser\fR(8)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwuser\fR(8),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5),
\fBrepquota\fR(8),
\fBsetquota\fR(8),
\fBshadow\fR(5)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2002-2013 Kai Wilke
.br
