.\"     Title: KWVCDBURNRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 12/04/2013
.\"    Manual: Benutzer Anleitung
.\"    Source: Version 0.0.9
.\"
.TH "KWVCDBURNRC" "5" "12/04/2013" "Version 0.0.9" "Benutzer Anleitung"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwvcdburnrc \- Konfigurationsdatei f\(:ur kwvcdburn.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwvcdburn\fR
wird die Datei
\fI~/\&.kwtools/kwvcdburnrc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwvcdburn\fR
ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBFILM_DIR\fR
.RS 4
Geben Sie hier das Grundverzeichnis an, in welchem die Filme gespeichert werden sollen\&. Ist die Variable nicht belegt wird das Homeverzeichnis benutzt\&.
.RE
.PP
\fBVCD_TYPE\fR
.RS 4
Angabe des VCD Types der benutzt werden soll (\fBsvcd,vcd1,vcd2,hqvcd\fR)\&. Standard ist
\(lq\fBsvcd\fR\(rq\&.
.RE
.PP
\fBMOUNT_PATH\fR
.RS 4
Angabe des Verzeichnis welches gemountet werden muss, z\&. B\&. weil Ihre Filme dort liegen und es nicht regelm\(:assig eingebunden ist\&. Dieses muss in der Datei
\fI/etc/fstab\fR
eingetragen sein\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwvcdburnrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwvcdburn\fR
F\(:ur weitere Details siehe
\fBkwvcdburn\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwvcdburn\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
