.\"     Title: KWVMSTATRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/16/2013
.\"    Manual: Benutzer Anleitung
.\"    Source: Version 0.3.0
.\"
.TH "KWVMSTATRC" "5" "11/16/2013" "Version 0.3.0" "Benutzer Anleitung"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwvmstatrc \- Konfigurationsdatei f\(:ur kwvmstat.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwvmstat\fR
wird die Datei
\fI~/\&.kwtools/kwvmstatrc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwvmstat\fR
ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBCOUNTER\fR
.RS 4
Anzahl der Aktualisierungen\&.
\fB0\fR
geht nicht,
\fBnichts\fR
ist eine Endlos Anzeige die man mit
\fISTRG+C\fR
beenden kann\&.
.RE
.PP
\fBDELAY\fR
.RS 4
Nummer f\(:ur die Verz\(:ogerung der Aktualisierungen in Sekunden\&.
\fB0\fR
geht nicht\&.
.RE
.PP
\fBMEM_UNIT\fR
.RS 4
Speichereinheit der Anzeige\&.
\fBk\fR
\-
\fI1Kb=1000b\fR,
\fBK\fR
\-
\fI1Kb=1024b\fR,
\fBm\fR
\-
\fI1Mb=1000000b\fR,
\fBM\fR
\-
\fI1Mb=1048576b\fR\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwvmstatrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwvmstat\fR
F\(:ur weitere Details siehe
\fBkwvmstat\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwvmstat\fR(1),
\fBvmstat\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
