#! /usr/bin/env zsh -f

######################################################################################################
#                                                                                                    #
#    ZAEMONSH Created by Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2017.         #
#    Copyright (c) 2017. All rights reserved.                                                        #
#    Hardly inspired by zsh-templates created by William Scott on May 11, 2007.                      #
#    Copyright (c) 2007. All rights reserved.                                                        #
#                                                                                                    #
#    This program is free software; you can redistribute it and/or modify                            #
#    it under the terms of the GNU General Public License as published By                            #
#    the Free Software Foundation; either version 2 of the License, or                               #
#    (at your option) any later version.                                                             #
#                                                                                                    #
#    This program is distributed in the hope that it will be useful,                                 #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of                                  #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                   #
#    GNU General Public License for more details.                                                    #
#                                                                                                    #
#    You should have received a copy of the GNU General Public License                               #
#    along with this program; if not, write to the Free Software                                     #
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301                       #
#    USA                                                                                             #
#                                                                                                    #
#    cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                                       #
#                                                                                                    #
######################################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# :

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
local VERSION

VERSION=
FCT_NAME=testFct

local banner 

#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
  clear
  echo "${NC}"
  echo " ###################################################################################################"
  echo " #                                                                                                 #"
  echo " #     ${GREEN}This is ${RED}$FCT_NAME : ${YEL}$VERSION FOR $OSTYPE ${NC}                                                  #"
  echo " #     CopyL®®v 2017, Zucchelli Bryan                                                              #"
  echo " #                                                                                                 #"
  echo " #     Unless required by applicable law or agreed to in writing, software                         #"
  echo " #     distributed under the License is distributed on an "AS IS" BASIS,                             #"
  echo " #     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                    #"
  echo " #     See the License for the specific language governing pe$RMissions and                                  #"
  echo " #     limitations under the License.                                                              #"
  echo " #                                                                                                 #"
  echo " ###################################################################################################"
  echo ""
} 

#----------------------------------------------------------------------------------------------------#
#                                               SCRIPT
#----------------------------------------------------------------------------------------------------#
banner
