.\"     Title: CREATE.CAL.PL
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Handbuch f\(:ur create.cal.pl
.\"    Source: Version 0.0.6
.\"
.TH "CREATE\&.CAL\&.PL" "1" "11/13/2013" "Version 0.0.6" "Handbuch f\(:ur create.cal.pl"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
create.cal.pl \- ein Perl Script f\(:ur die Scripte kwplaner/kwtex-cal.
.SH "SYNTAX"
.HP 14
\fBcreate\&.cal\&.pl\fR [\fB\-adfhqQvw\fR] [\fB\-b\fR\ <\fIBL\fR>] [\fB\-o\fR\ <\fIDatei\fR>] [\fB\-y\fR\ <\fIJahr\fR>]
.SH "BESCHREIBUNG"
.PP
\fBcreate\&.cal\&.pl\fR
ist ein Perl Script das einen
\fIPDF\fR
Kalender mit Feiertagen erzeugt\&. Dieses Script und auch die anderen Dateien dazu werden von Rene Scholz geschrieben/gepflegt\&. Die neueste Version k\(:onnen Sie sich unter folgender Adresse herunter laden:
.sp
.RS 4
.nf
http://www\&.thur\&.de/~Voland/pub/perl/
.fi
.RE
.SH "OPTIONEN"
.PP
\fB\-a\fR
.RS 4
Erstelle alle Feiertage, auch Gedenktage\&.
.RE
.PP
\fB\-b\fR <\fIBL\fR>
.RS 4
Erstelle alle Feiertage vom dementsprechenden Bundesland <\fIBL\fR>, (Beispiel:
\fB\-b\fR
\fIDE_HA\fR
= Deutschland/Hamburg)\&. Mit
\fBgcal\fR
\fB\-\-usage\fR=\fIcc\fR
kann man sich alle Staaten/Bundesl\(:ander anzeigen lassen\&.
.RE
.PP
\fB\-d\fR
.RS 4
Erstellt eine Beschreibung unter der Tabelle\&.
.RE
.PP
\fB\-f\fR
.RS 4
Erstellt einen Rahmen um die Beschreibung\&.
.RE
.PP
\fB\-h\fR
.RS 4
Anzeige der Hilfe\&.
.RE
.PP
\fB\-o\fR <\fIDatei\fR>
.RS 4
Erstelle dazu eigene Feiertage/Geburtstage von Datei <\fIDatei\fR>\&. Das Format der Datei sollte so aussehen: Kai Geburtstag + 1971\-04\-01
.RE
.PP
\fB\-q\fR
.RS 4
Zeige nicht den Output von latex etc\&.
.RE
.PP
\fB\-Q\fR
.RS 4
Zeige \(:uberhaupt keinen Output ausser von Fehlern\&.
.RE
.PP
\fB\-v\fR
.RS 4
Zeige Version von
\fBcreate\&.cal\&.pl\fR\&.
.RE
.PP
\fB\-w\fR
.RS 4
Schwarz/weiss, benutzt keine Farbe f\(:ur den Text\&.
.RE
.PP
\fB\-y\fR <\fIJahr\fR>
.RS 4
Generiert einen Kalender f\(:ur das Jahr <\fIJahr\fR>\&.
.RE
.SH "DATEI"
.PP
\fI/usr/share/kwtools/data/calendar/calendar\&.tex\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBcreate\&.cal\&.pl\fR
zum erstellen des Kalenders\&. F\(:ur weitere Details siehe
\fBkwtex-cal\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcalendar\fR(1),
\fBgcal\fR(1),
\fBkwtex-cal\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
