.\"     Title: KWDJBDNS
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Handbuch f\(:ur kwdjbdns
.\"    Source: Version 0.3.6
.\"
.TH "KWDJBDNS" "1" "11/12/2013" "Version 0.3.6" "Handbuch f\(:ur kwdjbdns"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwdjbdns \- ein Zshell Script f\(:ur die Administration von Dan Bernstein's DNS Servern.
.SH "SYNTAX"
.HP 9
\fBkwdjbdns\fR
.SH "BESCHREIBUNG"
.PP
\fBkwdjbdns\fR
soll Ihnen helfen die Konfiguration der verschiedenen
\fIDNS\fR\-Servern, von Prof\&.
\fBDan Bernstein\fR, zu bew\(:altigen und zu verwalten\&. Zuvor sollten Sie die
\fBdaemontools\fR,
\fBucspi\-tcp\fR
und
\fBdjbdns\fR
installieren\&. Entweder von
.sp
.RS 4
.nf
http://cr\&.yp\&.to
.fi
.RE
.sp
oder von einem Debian Server\&. Wenn nicht bei der Installation geschehen, legen Sie bitte die Accounts
\fIdnslog\fR
und die Servernamen, mit der Gruppen ID 65534 (\fInogroup\fR) an\&.
.PP
\fBNotiz:\fR
Es gibt die
\fIDNS\fR\-Server
\fBdnscache\fR,
\fBtinydns\fR,
\fBaxfrdns\fR,
\fBrbldns\fR
und
\fBwalldns\fR\&.
.SH "OPTIONEN"
.PP
\fBkwdjbdns\fR hat keine Kommandozeilen Optionen.
.SH "BUGS"
.PP
Wenn man einen Server l\(:oscht, l\(:auft der Supervise Daemon f\(:ur diesen weiter\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBaxfrdns\fR(8),
\fBdnscache\fR(8),
\fBrbldns\fR(8),
\fBtinydns\fR(8),
\fBwalldns\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
