.\"     Title: KWGPGCRYPT
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Handbuch f\(:ur kwgpgcrypt
.\"    Source: Version 0.0.8
.\"
.TH "KWGPGCRYPT" "1" "11/12/2013" "Version 0.0.8" "Handbuch f\(:ur kwgpgcrypt"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwgpgcrypt \- ein Zshell Frontend zu gnupg.
.SH "SYNTAX"
.HP 11
\fBkwgpgcrypt\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwgpgcrypt\fR
k\(:onnen Sie die folgenden Abl\(:aufe steuern\&. Dabei wird ihr Mantra (Passphrase) abgefragt\&. Sie sollten diesen vorher schon erstellt haben\&. Genaueres gibts dazu in der Manpage von
\fBgnupg\fR
(\fBgpg\fR(1))\&. Die Variable die den Mantra enth\(:alt wird sofort nach jeder Aktion gel\(:oscht\&.
.PP
\fBNotiz:\fR
Zuerst muss man sich daf\(:ur entscheiden, ob man ein ganzes Verzeichnis oder nur einzelne Dateien behandeln will\&. Dabei wird nachgefragt, ob die Originaldateien gel\(:oscht werden sollen\&.
.SH "OPTIONEN"
.PP
\fBkwgpgcrypt\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI~/\&.gnupg/options\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBgnupg\fR
<1\&.2\&.5\&.
.RE
.PP
\fI~/\&.gnupg/gpg\&.conf\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBgnupg\fR
>=1\&.2\&.5\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBgpg\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
