.\"     Title: KWMUTTPRINTCF
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Handbuch f\(:ur kwmuttprintcf
.\"    Source: Version 0.0.3
.\"
.TH "KWMUTTPRINTCF" "1" "11/12/2013" "Version 0.0.3" "Handbuch f\(:ur kwmuttprintcf"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwmuttprintcf \- Konfiguration des Programms Muttprint
.SH "SYNTAX"
.HP 14
\fBkwmuttprintcf\fR
.SH "BESCHREIBUNG"
.PP
\fBkwmuttprintcf\fR
konfiguriert das Programm
\fBmuttprint\fR\&.
.SH "OPTIONEN"
.PP
\fBkwmuttprintcf\fR hat keine Kommandozeilen Optionen.
.SH "DATEI"
.PP
\fI~/\&.muttprintrc\fR
.RS 0
Dies ist die Konfigurations Datei f\(:ur
\fBmuttprint\fR
F\(:ur weitere Details siehe
\fBmuttprint\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBmutt\fR(1),
\fBmuttprint\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
