.\"     Title: KWMUTT
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Handbuch f\(:ur kwmutt
.\"    Source: Version 0.0.8
.\"
.TH "KWMUTT" "1" "11/12/2013" "Version 0.0.8" "Handbuch f\(:ur kwmutt"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwmutt \- Konfiguration des Programms Mutt
.SH "SYNTAX"
.HP 7
\fBkwmutt\fR
.SH "BESCHREIBUNG"
.PP
\fBkwmutt\fR
konfiguriert das Programm
\fBmutt\fR, verwaltet das Adressbuch, Mailinglisten oder startet eine der verf\(:ugbaren Postf\(:acher\&.
.SH "OPTIONEN"
.PP
\fBkwmutt\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI~/\&.kwtools/kwmuttrc\fR
.RS 4
Dies ist die lokale Haupt\-Konfigurationsdatei f\(:ur
\fBmutt\fR\&. F\(:ur weitere Details siehe
\fBmuttrc\fR(5)\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/address\fR
.RS 4
Dies ist das
\fBmutt\fR
eigene Adressbuch\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/charsethooks\fR
.RS 4
Datei f\(:ur die Einstellung von "Aliasen" zu "Zeichens\(:atzen", die
\fBmutt\fR
vom Namen her nicht kennt\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/colors\fR
.RS 4
Datei f\(:ur die Farbeinstellung von
\fBmutt\fR\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/crypt\fR
.RS 4
Datei f\(:ur die Einstellung von
\fIPGP\fR
und
\fIS/MIME\fR
verschl\(:usselten Nachrichten\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/fcchooks\fR
.RS 4
Datei f\(:ur die Einstellung zum speichern einer Kopie von einer versendeten Nachricht\&. \(:Uberschreibt die Variable
\fBrecord\fR\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/fccsavehooks\fR
.RS 4
Datei f\(:ur die Einstellung zum speichern einer Kopie von einer versendeten Nachricht\&. Dies ist ein aequalent zur gleichzeitigen Ausf\(:uhrung von den Einstellungen in
\fIfcchooks\fR
und
\fIsavehooks\fR\&. \(:Uberschreibt die Variable
\fBrecord\fR\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/folderhooks\fR
.RS 4
Datei f\(:ur die Einstellung der Mailboxen\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/format\fR
.RS 4
Datei f\(:ur die Formatierung von Anzeigen bei
\fBmutt\fR\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/gpg\fR
.RS 4
Datei f\(:ur die Einstellung von
\fIPGP/MIME\fR
verschl\(:usselten Nachrichten\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/[Rechnername|IP]\&.imap\fR
.RS 4
Einstellungen f\(:ur den
\fIIMAP\fR\-Server mit der jeweiligen
\fIIP\fR
oder
\fIRechnernamen\fR\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/*\&.lmb\fR
.RS 4
Dateien mit den Einstellungen f\(:ur lokale Postf\(:acher\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/mailinglists\fR
.RS 4
Datei die die Mailinglisten enth\(:alt\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/mboxhooks\fR
.RS 4
Datei f\(:ur die Einstellung zum speichern der Nachrichten einer Mailbox in eine andere\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/messagehooks\fR
.RS 4
Datei f\(:ur die Einstellung wie Nachrichten auf bestimmte Muster angezeigt werden sollen\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/mkbd\fR
.RS 4
Datei die zust\(:andig ist f\(:ur die Tastenbelegung die im Index, Men\(:u, Pager, \&.\&.\&. zur Anwendung kommt\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/pager\fR
.RS 4
Datei f\(:ur die Einstellung des Pagers\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/[Rechnername|IP]\&.pop\fR
.RS 4
Einstellungen f\(:ur den
\fIPOP\fR\-Server mit der jeweiligen
\fIIP\fR
oder
\fIRechnernamen\fR\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/print\fR
.RS 4
Datei f\(:ur die Druckeinstellung von
\fBmutt\fR\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/savehooks\fR
.RS 4
Datei f\(:ur die Einstellung beim speichern von Nachrichten\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/sendhooks\fR
.RS 4
Datei f\(:ur die Einstellung der Header beim versenden von Nachrichten\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/score\fR
.RS 4
Datei f\(:ur die Einstellung der Anzeige nach einer Punkte\-Bewertung\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/[Rechnername|IP]\&.smtp\fR
.RS 4
Datei die zust\(:andig ist f\(:ur die Versendung der Mails per SMTP Server\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/*\&.smtp\fR
.RS 4
Alle anderen Dateien mit der Endung
\fIsmtp\fR
sind f\(:ur die Versendung der Mails per
\fBsendmail\fR\-Kommando zust\(:andig\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/signature\fR
.RS 4
Datei die die Standard Signatur f\(:ur die Mail enth\(:alt\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/smime\fR
.RS 4
Datei f\(:ur die Einstellung von
\fIS/MIME\fR
verschl\(:usselten Nachrichten\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/sort\fR
.RS 4
Datei die zust\(:andig ist f\(:ur die Sortierung der Baumansicht\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/ssl\fR
.RS 4
Datei f\(:ur die Einstellung von
\fISSL/TLS\fR
Verbindungen\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/unignore_headers\fR
.RS 4
Datei f\(:ur die Einstellung von
\fBHeader\fR
die angezeigt werden sollen\&. Standardm\(:assig werden alle
\fBHeader\fR
bei der Anzeige ignoriert\&.
.RE
.PP
\fI~/\&.kwtools/kwmutt/urlview\fR
.RS 4
Datei f\(:ur die Einstellung von
\fBurlview\fR\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwmuttprintcf\fR(1),
\fBmutt\fR(1),
\fBmuttprint\fR(1),
\fBmuttrc\fR(5)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
