.\"     Title: KWNETSTAT
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Handbuch f\(:ur kwnetstat
.\"    Source: Version 0.2.14
.\"
.TH "KWNETSTAT" "1" "11/12/2013" "Version 0.2.14" "Handbuch f\(:ur kwnetstat"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwnetstat \- ein Frontend Script f\(:ur netstat.
.SH "SYNTAX"
.HP 10
\fBkwnetstat\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwnetstat\fR
k\(:onnen Sie einige Informationen \(:uber Ihr Netzwerk, zum jetzigen Zeitpunkt, sammeln\&. Es wird das Programm
\fBnetstat\fR
daf\(:ur benutzt\&.
.PP
Die einzelnen Optionen k\(:onnen meist gemixt werden\&. Nur
\(lq\fBi\fR\(rq,
\(lq\fBr\fR\(rq
und
\(lq\fBs\fR\(rq
m\(:ussen einzeln ausgew\(:ahlt werden\&.
.PP
Als normaler Benutzer k\(:onnen nicht\-eigene Prozesse angezeigt werden\&.
.SH "OPTIONEN"
.PP
\fBkwnetstat\fR hat keine Kommandozeilen Optionen.
.SH "SIEHE AUCH"
.PP
\fBnetstat\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
