'\" t
.\"     Title: KWPOSTFIX
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Handbuch f\(:ur kwpostfix
.\"    Source: Version 0.1.15
.\"  Language: English
.\"
.TH "KWPOSTFIX" "1" "11/12/2013" "Version 0.1.15" "Handbuch f\(:ur kwpostfix"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwpostfix \- Administration des Mail Transfer Agenten (MTA) postfix\&.
.SH "SYNTAX"
.HP \w'\fBkwpostfix\fR\ 'u
\fBkwpostfix\fR
.SH "BESCHREIBUNG"
.PP
\fBkwpostfix\fR
ist ein Frontend, zur Administration des MTA
\fBpostfix\fR\&. Es kann \(:uber 300 Parameter konfigurieren und mehr als 25 Tabellen bearbeiten\&. Es unterst\(:utzt alle Tabellentypen und deren Syntax\&.
.PP
\fBNotiz:\fR
Man kann noch nicht alle Tabellen, die man in der Datei
\fI/etc/postfix/main\&.cf\fR
angeben kann, konfigurieren\&. Nur die haupts\(:achlichsten\&. Ausserdem konnte der Tabellentyp
\(lq\fBldap\fR\(rq
noch nicht getestet werden\&.
.SH "OPTIONEN"
.PP
\fBkwpostfix\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI/etc/postfix/main\&.cf\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur alle Parameter von
\fBpostfix\fR\&.
.RE
.PP
\fI/etc/postfix/master\&.cf\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur alle Prozesse von
\fBpostfix\fR\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBpostfix\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2002-2013 Kai Wilke
.br
