.\"     Title: KWRECORD
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwrecord
.\"    Source: Version 0.1.27
.\"
.TH "KWRECORD" "1" "11/13/2013" "Version 0.1.27" "Benutzerhandbuch f\(:ur kwrecord"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwrecord \- Zshell Script zum brennen.
.SH "SYNTAX"
.HP 9
\fBkwrecord\fR
.SH "BESCHREIBUNG"
.PP
\fBkwrecord\fR
dient zum brennen von Dateien und Verzeichnissen, unterschiedlicher Formate\&. Dabei sind die Bereiche in verschiedene Bereiche unterteilt\&. Nachdem brennen werden Sie gefragt, ob die Original Dateien gel\(:oscht werden sollen? Das betrifft in diesen F\(:allen nur die erzeugten
\fIISO\fR
Images oder die fuer
\fBcdrdao\fR
erzeugten
\fITOC\fR\-Dateien\&. In allen F\(:allen wird gepr\(:uft ob eine
\fICD\fR
oder
\fIDVD\fR
im Laufwerk ist und ob es ein Rohling oder schon ein beschriebenes Medium ist\&.
.PP
\fBNotiz:\fR
Bei
\fImp3/ogg\fR
und
\fIPhoto\fR
Dateien d\(:urfen keine Dateiennamen doppelt vorkommen, sonst erstellt
\fBgenisoimage\fR
kein Image\&. Multisession
\fICD/DVDs\fR
werden noch nicht unterst\(:utzt, wie auch einige andere neue Features\&.
.SH "OPTIONEN"
.PP
\fBkwrecord\fR hat keine Kommandozeilen Optionen.
.SH "DATEI"
.PP
\fI~/\&.kwtools/cd_dvdrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur alle kwtools Scripts die brennen k\(:onnen\&. F\(:ur weitere Details siehe
\fBcd_dvdrc\fR(5)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcd_dvdrc\fR(5),
\fBcdrdao\fR(1),
\fBgenisoimage\fR(1),
\fBgrowisofs\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
