.\"     Title: KWRIP
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwrip
.\"    Source: Version 0.0.9
.\"
.TH "KWRIP" "1" "11/13/2013" "Version 0.0.9" "Benutzerhandbuch f\(:ur kwrip"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwrip \- ein Zshell Script zum CDs rippen.
.SH "SYNTAX"
.HP 6
\fBkwrip\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwrip\fR
k\(:onnen Sie Audio\- und Video\-CDs rippen\&. Ein Basis Verzeichnis kann man in der Konfiguration einstellen\&. Dadurch hat man nicht soviel Arbeit beim einstellen des Verzeichnisses in das die Filme oder Musik gerippt werden sollen\&.
.SH "OPTIONEN"
.PP
\fBkwrip\fR hat keine Kommandozeilen Optionen.
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwriprc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwrip\fR\&. F\(:ur weitere Details siehe
\fBkwriprc\fR(5)\&.
.RE
.SH "BUGS"
.PP
\fBkwrip\fR
kann keine Video\-CDs rippen die mit einigen Windows Programmen erstellt worden sind\&. H\(:angt vom Programm ab\&.
.SH "SIEHE AUCH"
.PP
\fBcddbcmd\fR(1),
\fBcd_discid\fR(1),
\fBcdparanoia\fR(1),
\fBkwriprc\fR(5),
\fBlame\fR(1),
\fBoggenc\fR(1),
\fBvcdxrip\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
