.\"     Title: KWSSL2
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwssl2
.\"    Source: Version 0.0.2
.\"  Language: English
.\"
.TH "KWSSL2" "1" "11/13/2013" "Version 0.0.2" "Benutzerhandbuch f\(:ur kwssl2"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwssl2 \- ein Zshell Script zur Verwaltung von Zertifizierungsstelle (CA)\&.
.SH "SYNTAX"
.HP \w'\fBkwssl2\fR\ 'u
\fBkwssl2\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwssl2\fR
k\(:onnen Sie mittels dem Programm
\fBopenssl\fR
\(lqZertifizierungsstellen\(rq
(CAs \- Certification Authority) erzeugen und verwalten\&.
.SH "OPTIONEN"
.PP
\fBkwssl2\fR
besitzt keine Komandozeilen Optionen\&.
.SH "DATEIEN"
.PP
\fI~/\&.kwtools/kwssl2\fR
.RS 4
Speicherort f\(:ur die CAs und deren Dateien\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBopenssl\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2012-2013 Kai Wilke
.br
