.\"     Title: KWTERMIN
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwtermin
.\"    Source: Version 0.1.2
.\"
.TH "KWTERMIN" "1" "11/13/2013" "Version 0.1.2" "Benutzerhandbuch f\(:ur kwtermin"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwtermin \- ein Zshell Script f\(:ur das Script kwplaner.
.SH "SYNTAX"
.HP 9
\fBkwtermin\fR
.SH "BESCHREIBUNG"
.PP
\fBkwtermin\fR
ist ein client\-script, mit deren Hilfe man seine Termine verwalten kann\&. Termine werden per mail gemeldet, wenn man m\(:ochte\&. Geben Sie also immer Ihre
\fBMailadresse\fR
an\&. Die Konfiguration kann man bequem \(:uber das Script
\fBkwplaner\fR
erledigen\&.
.SH "OPTIONEN"
.PP
\fBkwtermin\fR hat keine Kommandozeilen Optionen.
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwplanerrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwholiday\fR,
\fBkwplaner\fR,
\fBkwtermin\fR
und
\fBkwtex\-cal\fR\&. F\(:ur weitere Details siehe
\fBkwplanerrc\fR(5)\&.
.RE
.PP
\fI~/\&.kwtools/kwplaner/termin\fR
.RS 4
Dies ist die Datei die die Termine enth\(:alt\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcalendar\fR(1),
\fBkwplaner\fR(1),
\fBkwplanerrc\fR(5),
\fBkwtex-cal\fR(1),
\fBkwtermin_cron\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
