.\"     Title: KWTERMIN_CRON
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Handbuch f\(:ur kwtermin_cron
.\"    Source: Version 0.1.4
.\"
.TH "KWTERMIN_CRON" "1" "11/13/2013" "Version 0.1.4" "Handbuch f\(:ur kwtermin_cron"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwtermin_cron \- ein Crontab Script f\(:ur das Script kwtermin.
.SH "SYNTAX"
.HP 14
\fBkwtermin_cron\fR
.SH "BESCHREIBUNG"
.PP
\fBkwtermin_cron\fR
ist eine Art Termin\-Server, mit deren Hilfe man sich seine Termine rechtzeitig per mail zukommen lassen kann\&. Dieses Script wird einmal pro Minute vom
\fBCron\fR
Daemon aufgerufen\&. Dies k\(:onnen Sie mit dem Script
\fBkwtermin\fR
einstellen\&. Es steht dann in ihrer eigenen
\fIcrontab\fR
Tabelle\&.
.SH "OPTIONEN"
.PP
\fBkwtermin_cron\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI~/\&.kwtools/kwplanerrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwholiday\fR,
\fBkwplaner\fR,
\fBkwtermin\fR
und
\fBkwtex\-cal\fR\&. F\(:ur weitere Details siehe
\fBkwplanerrc\fR(5)\&.
.RE
.PP
\fI~/\&.kwtools/kwplaner/termin\fR
.RS 4
Dies ist die Datei die die Termine enth\(:alt\&. F\(:ur weitere Details siehe
\fBkwtermin\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcron\fR(8),
\fBcrontab\fR(1),
\fBcrontab\fR(5),
\fBkwplaner\fR(1),
\fBkwplanerrc\fR(5),
\fBkwtermin\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2008 Kai Wilke
.br
