.\"     Title: KWTEX-CAL
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwtex-cal
.\"    Source: Version 0.2.13
.\"
.TH "KWTEX\-CAL" "1" "11/13/2013" "Version 0.2.13" "Benutzerhandbuch f\(:ur kwtex-cal"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwtex-cal \- ein Zshell Script fuer das Script kwplaner.
.SH "SYNTAX"
.HP 10
\fBkwtex\-cal\fR
.SH "BESCHREIBUNG"
.PP
\fBkwtex\-cal\fR
ist ein Frontend f\(:ur das Perl Script
\fBcreate\&.cal\&.pl\fR
und deren
\fITex\fR
Dateien (\fBtex\-cal\fR) von Rene Scholz\&.
.sp
.RS 4
.nf
http://www\&.thur\&.de/~Voland/pub/perl/tex\-cal
.fi
.RE
.PP
\fBkwtex\-cal\fR
kann einen Jahreskalender mit Bildern erzeugen und auch ausdrucken\&. Bilder kann man im Verzeichnis
\fI~/\&.kwtools/kwplaner/pics\fR
ablegen\&. Diese m\(:ussen die Formate "\fBeps\fR", "\fBjpg\fR" oder "\fBpng\fR" haben\&.
.PP
Es m\(:ussen 13 St\(:uck sein, 12 Monate+1 Deckblatt\&. Die Bilder werden automatisch in die richtige Gr\(:osse konvertiert, wenn Sie nicht gr\(:osser als eine Postkarte sind\&. Sie brauchen nur das dementsprechende Jahr ausw\(:ahlen\&. Gibt es keine Konfiguration wird das aktuelle Jahr und das Bundesland Deutschland/Hamburg benutzt\&.
.PP
\fBNotiz:\fR
Die Konfiguration erfolgt \(:uber das Script
\fBkwplaner\fR, welches verschiedene Scripts zusammenfasst\&.
.PP
Gibt es keine Konfiguration wird das aktuelle Jahr und das Bundesland Deutschland/Hamburg benutzt\&.
.SH "OPTIONEN"
.PP
\fBkwtex-cal\fR hat keine Kommandozeilen Optionen.
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwplanerrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwholiday\fR,
\fBkwplaner\fR,
\fBkwtermin\fR
und
\fBkwtex\-cal\fR\&. F\(:ur weitere Details siehe
\fBkwplanerrc\fR(5)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcreate.cal.pl\fR(1),
\fBkwplaner\fR(1),
\fBkwplanerrc\fR(5),
\fBkwtermin\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
