.\"     Title: KWVCDBURN
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 12/04/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwvcdburn
.\"    Source: Version 0.0.9
.\"
.TH "KWVCDBURN" "1" "12/04/2013" "Version 0.0.9" "Benutzerhandbuch f\(:ur kwvcdburn"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwvcdburn \- ein Zshell Script f\(:ur Video-CDs.
.SH "SYNTAX"
.HP 10
\fBkwvcdburn\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwvcdburn\fR
k\(:onnen Sie ihre MPEG Filme in verschiedene Video CD Formate konvertieren und anschliessend auf
\fICD\fR
brennen\&. Zum Brennen benutzt
\fBkwvcdburn\fR
das Programm
\fBcdrdao\fR
und zur Video CD Erstellung
\fBvcdimager\fR\&.
.SH "OPTIONEN"
.PP
\fBkwvcdburn\fR hat keine Kommandozeilen Optionen.
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwvcdburnrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwvcdburn\fR\&. F\(:ur weitere Details siehe
\fBkwvcdburnrc\fR(5)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwrecord\fR(1),
\fBkwvcdburnrc\fR(5),
\fBvcdimager\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
