.\"     Title: KWXMMS2D
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwxmms2d
.\"    Source: Version 0.0.3
.\"  Language: English
.\"
.TH "KWXMMS2D" "1" "11/13/2013" "Version 0.0.3" "Benutzerhandbuch f\(:ur kwxmms2d"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwxmms2d \- Ein Frontend Script f\(:ur \(lqxmms2d\(rq\&.
.SH "SYNTAX"
.HP \w'\fBkwxmms2d\fR\ 'u
\fBkwxmms2d\fR
.SH "BESCHREIBUNG"
.PP
\fBkwxmms2d\fR
ist ein Frontend f\(:ur
\fBxmms2d\fR\&. Es kann die Server Adresse einstellen und diesen starten und stoppen\&.
.SH "OPTIONEN"
.PP
\fBkwxmms2d\fR hat keine Kommandozeilen Optionen.
.SH "SIEHE AUCH"
.PP
\fBkwxmms2\fR(1),
\fBxmms2\fR(1),
\fBxmms2d\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2010-2013 Kai Wilke
.br
