#! /usr/bin/env zsh -f

##########################################################################################
#                                                                                        #
#  ZaemonSH created by :                                                                 #
#  Zucchelli Bryan && @N@TOME && Admiral Gr@ss H0pper on Oct 13, 2016.                   #
#  Copyright (c) 2019. All rights reserved.                                              #
#  Inspired by zsh-templates-osx created by :                                            #
#  William Scott on May 11, 2007.                                                        #
#  Copyright (c) 2007. All rights reserved.                                              #
#                                                                                        #
#  This program is free software; you can redistribute it and/or modify it under         #
#  the terms of the GNU General Public License as published by the Free Software         #
#  Foundation; either version 2 of the License, or (at your option) any later version.   #
#                                                                                        #
#  This program is distributed in the hope that it will be useful, but WITHOUT           #
#  ANY WARRANTY ; without even the implied warranty of MERCHANTABILITY or                #
#  FITNESS FOR A PARTICULAR PURPOSE.                                                     #
#  See the GNU General Public License for more details.                                  #
#                                                                                        #
#  You should have received a copy of the GNU General Public License                     #
#  along with this program ; if not, write to the Free Software Foundation,              #
#  Inc., 51 Franklin Street, Fifth Floor, Boston,  MA 02110-1301 USA                     #
#                                                                                        #
#  cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html                             #
#                                                                                        #
##########################################################################################

#----------------------------------------------------------------------------------------#
#                                     DESCRIPTION
#----------------------------------------------------------------------------------------#
# quit :
# By Wataru Kagawa (05/17/05)
# wkagawa@jota.gsc.riken.go.jp
#
# A function to quit Mac OS X applications.  Native applications are
# quitted using an osascript, and X11 applications are quitted by killing
# its pid.
# usage: quit [-f] application

#----------------------------------------------------------------------------------------#
#                                        TODO
#----------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------#
#                                       CHANGES
#----------------------------------------------------------------------------------------#
# 04/01/2018 :
#  • Modify function presentation.

#----------------------------------------------------------------------------------------#
#                                       CONFIG
#----------------------------------------------------------------------------------------#
#######################
## COMMAND VARIABLES ##
#######################
local VERSION FCT_NAME

VERSION="0.0.1"
FCT_NAME="$(echo $0)"


local SelectedApp USAGE_TEXT tsess pid
#----------------------------------------------------------------------------------------#
#                                      FUNCTIONS
#----------------------------------------------------------------------------------------#
banner () {
     clear
     echo " ##############################################################################"
     echo " #                                                                            #"
     echo " #  ${GREEN}This is ${RED}$FCT_NAME: ${YEL}$VERSION on ${GREEN}$OSTYPE${NC}${YEL} system.${NC}"
     echo " #  CopyL®®v 2020, Zucchelli Bryan                                            #"
     echo " #                                                                            #"
     echo " #  Unless required by applicable law or agreed to in writing, software       #"
     echo " #  distributed under the License is distributed on an AS IS BASIS,           #"
     echo " #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  #"
     echo " #  See the License for the specific language governing permissions and       #"
     echo " #  limitations under the License.                                            #"
     echo " #                                                                            #"
     echo " ##############################################################################"
     echo ""
}

help(){
  cat<<__EOF__
  ${RED}
    usage: quit [ APPLICATION ]

    Examples: 
           quit Finder            # As eg hill the finder.
  ${NC}
__EOF__
}
#-------------------------------------------------------------------------------------------#
#                                              SCRIPT
#-------------------------------------------------------------------------------------------#
banner

#-----------------------------------------
# Updates the list of running applications
#-----------------------------------------
_get_running_apps


#--------------------------
# Retrieve application name
#--------------------------
SelectedApp=${${(f)@}#-f }


#----------------------------------------------------------
# Exits this function if application is missing or mistyped
#----------------------------------------------------------
USAGE_TEXT="
  ${RED}
  quit: options (-f) [application name]
	required arguments: [application name]
	Quits the currently running application.  All native applications are quitted by
	an osascript by default.  X11 applications are quitted by the kill command.

	-f, force quit application by killing its pid${NC}"

if [[ -z $SelectedApp || $@ == '-' || $@ == '-f' ]]; then
	print "${RED}Usage: $USAGE_TEXT${NC}"
	return 0
fi

if [[ -z ${(M)list:#$SelectedApp} ]]; then
	print "\e[1m${RED} No such application running. \e[0m"
	return 0
fi


#---------------------------------------------------------------------------------
# Quits the application either by using an osascript or by using the kill command.
#---------------------------------------------------------------------------------
tsess=$list[$list[(i)$SelectedApp]-1]
pid=$list[$list[(i)$SelectedApp]-2]

if [[ $1 == '-f' || $tsess != '0' ]]; then
	kill $pid
else
	osascript -e "tell application \"$SelectedApp\" to quit"
fi
