.\"     Title: KWAUTH
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwauth
.\"    Source: Version 0.0.2
.\"
.TH "KWAUTH" "8" "11/12/2013" "Version 0.0.2" "Benutzerhandbuch f\(:ur kwauth"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwauth \- ein Zshell Script zur Einstellung der Authentifizierung des Systems.
.SH "SYNTAX"
.HP 7
\fBkwauth\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwauth\fR
kann man die Authentifizierung des Systems \(:uber
\fIPAM\fR,
\fILDAP\fR
und
\fINIS\fR
einstellen falls die dementsprechenden Programme beziehungsweise richtigen PAM\-Module installiert sind\&.
.PP
Notiz: Bei
\fIOpenSuSE\fR
wird das Programm
\(lq\fByast2 \-> Netzwork Services\fR\(rq
benutzt und bei
\fIFedora\fR
und
\fICentOS\fR
das Programm
\fBauthconfig\-tui\fR\&.
.SH "OPTIONEN"
.PP
\fBkwauth\fR hat keine Kommandozeilen Optionen.
.SH "SIEHE AUCH"
.PP
\fBpam-auth-update\fR(8),
\fBldap.conf\fR(5)
\fByp.conf\fR(5)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2010-2013 Kai Wilke
.br
