.\"     Title: KWCLOCK
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwclock
.\"    Source: Version 0.1.21
.\"
.TH "KWCLOCK" "8" "11/12/2013" "Version 0.1.21" "Benutzerhandbuch f\(:ur kwclock"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwclock \- ein Zshell Script zur Einstellung der Uhrzeit und des Datums.
.SH "SYNTAX"
.HP 8
\fBkwclock\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwclock\fR
kann man die Uhrzeit, das Datum und ein oder mehrere Zeitserver einstellen\&.
.SH "OPTIONEN"
.PP
\fBkwclock\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI/etc/default/ntpdate\fR
.RS 4
Konfigurations Datei f\(:ur
\fBntpdate\fR
Distribution
\fBDebian\fR\&.
.RE
.PP
\fI/etc/sysconfig/ntpd\fR
.RS 4
Konfigurations Datei f\(:ur
\fBntpdate\fR
die Distributionen
\fBFedora\fR
und
\fBCentOS\fR\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBdate\fR(1),
\fBhwclock\fR(8),
\fBntpdate\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
