.\"     Title: KWCRYPT
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Handbuch f\(:ur kwcrypt
.\"    Source: Version 0.0.8
.\"
.TH "KWCRYPT" "8" "11/12/2013" "Version 0.0.8" "Handbuch f\(:ur kwcrypt"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwcrypt \- Zshell Wrapper Script f\(:ur die Scripte kwcryptsetup, kwecryptfs und kwlosetup.
.SH "SYNTAX"
.HP 8
\fBkwcrypt\fR
.SH "BESCHREIBUNG"
.PP
Sind die Scripte
\fBkwcryptsetup\fR,
\fBkwecryptfs\fR
und
\fBkwlosetup\fR
vorhanden werden sie zur Auswahl angeboten\&.
.SH "OPTIONEN"
.PP
\fBkwcrypt\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI~/\&.kwtools/kwcryptsetuprc\fR
.RS 4
Konfigurations Datei f\(:ur
\fBkwcryptsetup\fR\&. Siehe
\fBkwcryptsetuprc\fR(5)
f\(:ur weitere Details\&.
.RE
.PP
\fI~/\&.kwtools/kwecryptfsrc\fR
.RS 4
Konfigurations Datei f\(:ur
\fBkwecryptfs\fR\&. Siehe
\fBkwecryptfsrc\fR(5)
f\(:ur weitere Details\&.
.RE
.PP
\fI~/\&.kwtools/kwlosetuprc\fR
.RS 4
Konfigurations Datei f\(:ur
\fBkwlosetup\fR\&. Siehe
\fBkwlosetuprc\fR(5)
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcryptsetup\fR(8),
\fBcrypttab\fR(5),
\fBdmsetup\fR(8),
\fBkwcryptsetup\fR(8),
\fBkwcryptsetuprc\fR(5),
\fBkwecryptfs\fR(8),
\fBkwecryptfsrc\fR(5),
\fBkwlosetup\fR(1),
\fBkwlosetuprc\fR(5),
\fBlosetup\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
