.\"     Title: KWGROUP
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/12/2013
.\"    Manual: Handbuch f\(:ur kwgroup
.\"    Source: Version 0.2.6
.\"
.TH "KWGROUP" "8" "11/12/2013" "Version 0.2.6" "Handbuch f\(:ur kwgroup"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwgroup \- ein Zshell Script zur Gruppen Verwaltung.
.SH "SYNTAX"
.HP 8
\fBkwgroup\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwgroup\fR
k\(:onnen Sie Gruppen anlegen, ver\(:andern, l\(:oschen und sich die Datei
\fI/etc/group\fR
anschauen\&.
.SH "OPTIONEN"
.PP
\fBkwgroup\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI/etc/group\fR
.RS 4
Datei mit den Gruppen Informationen\&. Siehe
\fBgroup\fR(5)
f\(:ur weitere Details\&.
.RE
.PP
\fI/etc/gshadow\fR
.RS 4
Datei mit den sicheren Gruppen Informationen\&. Siehe
\fBgshadow\fR(5)
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBgroup\fR(5),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBgshadow\fR(5)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
