.\"     Title: KWLOGROTATE
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwlogrotate
.\"    Source: Version 0.3.0
.\"
.TH "KWLOGROTATE" "8" "11/13/2013" "Version 0.3.0" "Benutzerhandbuch f\(:ur kwlogrota"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwlogrotate \- ein Frontend Zshell Script f\(:ur logrotate.
.SH "SYNTAX"
.HP 12
\fBkwlogrotate\fR
.SH "BESCHREIBUNG"
.PP
\fBkwlogrotate\fR
Hier k\(:onnen Sie bequem ihre Logdateien verwalten, anlegen und l\(:oschen\&. Es werden nur die Dateien im Verzeichnis (meist)
\fI/etc/logrotate\&.d\fR
benutzt oder angelegt\&.
.PP
Eine Konfiguration der Hauptkonfigurationsdatei ist noch nicht vorhanden\&. Dieses Script schreibt die Logdatei jedesmal neu, heisst das kwlogrotate nicht alles unterst\(:utzt\&. Bei komplexeren Logdateien werden Sie eventuell ein paar Optionen, nach dem speichern vermissen\&. Konfigurieren Sie also am besten nur Ihre eigenen Dateien\&.
.SH "OPTIONEN"
.PP
\fBkwlogrotate\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI/var/lib/logrotate/status\fR
.RS 4
Status Datei von
\fBkwlogrotate\fR\&.
.RE
.PP
\fI/etc/logrotate\&.conf\fR
.RS 4
Haupt Konfigurations Datei f\(:ur
\fBkwlogrotate\fR\&. Siehe
\fBlogrotate\fR(8)
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBlogrotate\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
