.\"     Title: KWLVM
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwlvm
.\"    Source: Version 0.3.8
.\"
.TH "KWLVM" "8" "11/13/2013" "Version 0.3.8" "Benutzerhandbuch f\(:ur kwlvm"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwlvm \- ein Zshell Frontend f\(:ur lvm1 und lvm2.
.SH "SYNTAX"
.HP 6
\fBkwlvm\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwlvm\fR
k\(:onnen Sie Physikalische Volumes (\fBPV\fR), Volume Groups (\fBVG\fR) und logische Volumes (\fBLV\fR) erstellen, sich anzeigen lassen, vergr\(:ossern, verkleinern, zusammenf\(:ugen, splitten, verschieben und l\(:oschen\&.
.SH "OPTIONEN"
.PP
\fBkwlvm\fR hat keine Kommandozeilen Optionen.
.SH "SIEHE AUCH"
.PP
\fBlvm\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
