.\"     Title: KWNARCCONF
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch kwnarcconf
.\"    Source: Version 0.1.12
.\"
.TH "KWNARCCONF" "8" "11/13/2013" "Version 0.1.12" "Benutzerhandbuch kwnarcconf"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwnarcconf \- Konfigurations Frontend f\(:ur das Script kwnarc
.SH "SYNTAX"
.HP 11
\fBkwnarcconf\fR
.SH "BESCHREIBUNG"
.PP
\fBkwnarcconf\fR
ist ein Konfigurations Frontend f\(:ur das Script
\fBkwnarc\fR
\- kwtools Netfilter Automatic Rule Configurator\&. Es kann dialogbasiert
\fBkwnarc\fR
konfigurieren\&. Netfilter ist Ihre Firewall, die man mit
\fBiptables\fR, seit Kernel >=2\&.4, konfiguriert\&.
.SH "OPTIONEN"
.PP
\fBkwnarcconf\fR hat keine Kommandozeilen Optionen.
.SH "DATEI"
.PP
\fI/etc/kwtools/kwnarc\&.conf\fR
.RS 4
Haupt Konfiguration Datei f\(:ur
\fBkwnarc\fR\&. Siehe
\fBkwnarc.conf\fR(5)
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBiptables\fR(8),
\fBkwnarc\fR(8),
\fBkwnarc.conf\fR(5)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
