.\"     Title: KWPARTED
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 27/04/2015
.\"    Manual: Benutzerhandbuch f\(:ur kwparted
.\"    Source: Version 0.3.0
.\"
.TH "KWPARTED" "8" "27/04/2015" "Version 0.3.0" "Benutzerhandbuch f\(:ur kwparted"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwparted \- ein Zshell Frontend fuer parted
.SH "SYNTAX"
.HP 9
\fBkwparted\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwparted\fR
k\(:onnen Sie Ihre Partitionen verwalten\&. Dazu geh\(:oren anlegen, l\(:oschen, vergr\(:ossern, verkleinern, kopieren und Flags \(:andern\&. Es werden noch nicht alle Dateisysteme von
\fBparted\fR
und
\fBkwparted\fR
unterst\(:utzt\&. Schauen Sie dazu auf folgende Website:
.sp
.RS 4
.nf
http://www\&.gnu\&.org/software/parted/parted\&.html
.fi
.RE
.sp
oder in
\fBkwparted\fR
\->
\fBStatus\fR\&. Das vergr\(:ossern und verkleinern der Partitionen muss das Dateisystem auch unterst\(:utzen\&. So unterst\(:utzt das
\fIXFS\fR
Dateisystem keine Verkleinerung\&. Lesen Sie dazu die Dokumentation zu Ihrem Dateisystem\&.
.PP
\fBkwparted\fR
unterst\(:utzt auch noch nicht alle Dateisysteme, die der Kernel unterst\(:utzt\&. Zur Zeit gehen nur die Dateisysteme
\fIbtrfs\fR,
\fIexfat\fR,
\fIext2/3/4\fR,
\fIfat16/fat32\fR,
\fIhfs\fR,
\fIhfs+\fR,
\fIjfs\fR,
\fIlinux\-swap\fR,
\fIntfs\fR,
\fIreiserfs\fR,
\fIreiser4\fR,
\fIufs\fR
und
\fIxfs\fR
und dann auch nur wenn die dementsprechenden Dateisystem Werkzeuge oder Bibliotheken installiert sind\&.
.SH "OPTIONEN"
.PP
\fBkwparted\fR hat keine Kommandozeilen Optionen.
.SH "SIEHE AUCH"
.PP
\fBkwlvm\fR(8),
\fBkwraid\fR(8),
\fBparted\fR(8),
\fBpartprobe\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
