.\"     Title: KWPROXY
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Handbuch f\(:ur kwproxy
.\"    Source: Version 0.2.8
.\"
.TH "KWPROXY" "8" "11/13/2013" "Version 0.2.8" "Handbuch f\(:ur kwproxy"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwproxy \- ein Zshell Script zur Konfiguration des http/ftp Proxy.
.SH "SYNTAX"
.HP 8
\fBkwproxy\fR
.SH "BESCHREIBUNG"
.PP
\fBkwproxy\fR
konfiguriert die Umgebungsvariablen
\fBhttp_proxy\fR
und
\fBftp_proxy\fR\&. Diese werden von vielen Programmen benutzt\&. Bei SuSE sind diese gross geschrieben\&. Sie haben alle das Format:
\fBhttp_proxy\fR=\fIProtokoll://Rechner:Port\fR, oder
\fBhttp_proxy\fR=\fIProtokoll://Rechner\&.domain\&.tld:port\fR\&. Der
\fBftp_proxy\fR
kann auch der selbe wie der
\fBhttp_proxy\fR
sein\&. Die meisten Proxy unterst\(:utzen beide Protokolle\&.
.PP
Damit die Variablen eingelesen werden, m\(:ussen sie in die
\fI/etc/profile\fR
(alle shells),
\fI/etc/zsh/zprofile\fR
(zsh), in
\fI~/\&.(z)profile\fR
oder in die profile Datei einer Shell ihrer Wahl eingetragen werden\&. Beispiel:
\fBtest\fR
\fB\-e\fR
\fI/etc/default/proxy\fR
&&
\fBsource\fR
\fI/etc/default/proxy\fR\&.
.SH "OPTIONEN"
.PP
\fBkwproxy\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI/etc/default/proxy\fR
.RS 4
Konfigurations Datei f\(:ur Debian und grml\&.
.RE
.PP
\fI/etc/sysconfig/proxy\fR
.RS 4
Konfigurations Datei f\(:ur (Open)SuSE, CentOS und Fedora\&.
.RE
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
