.\"     Title: KWQUOTA
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwquota
.\"    Source: Version 0.0.10
.\"
.TH "KWQUOTA" "8" "11/14/2013" "Version 0.0.10" "Benutzerhandbuch f\(:ur kwquota"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwquota \- Frontend Script f\(:ur quota.
.SH "SYNTAX"
.HP 8
\fBkwquota\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwquota\fR
k\(:onnen Sie den Plattenplatz von Benutzern, Gruppen oder Projekten (\fIXFS\fR) verwalten\&.
.SH "OPTIONEN"
.PP
\fBkwquota\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI/etc/quotagrpadmins\fR
.RS 4
Datei die die Namen der Benutzer enth\(:alt die Gruppen administrieren d\(:urfen\&.
.RE
.PP
\fI/etc/quotatab\fR
.RS 4
Datei die die Laufwerks Beschreibung enth\(:alt\&.
.RE
.PP
\fI/etc/warnquota\&.conf\fR
.RS 4
Konfigurations Datei f\(:ur
\fBwarnquota\fR\&. Siehe
\fBwarnquota\fR(8)
und
\fI/usr/share/doc/quota/warnquota\&.conf\fR
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBquota\fR(8),
\fBrepquota\fR(8),
\fBsetquota\fR(8),
\fBwarnquota\fR(8),
\fBxfs_quota\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
