.\"     Title: KWRAID
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 05/21/2015
.\"    Manual: Benutzerhandbuch f\(:ur kwraid
.\"    Source: Version 0.4.0
.\"
.TH "KWRAID" "8" "05/21/2015" "Version 0.4.0" "Benutzerhandbuch f\(:ur kwraid"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwraid \- ein Zshell Script f\(:ur die Administration von RAID Arrays
.SH "SYNTAX"
.HP 7
\fBkwraid\fR
.SH "BESCHREIBUNG"
.PP
Mit dem Script
\fBkwraid\fR
k\(:onnen Sie RAID Arrays erstellen, Partitionen/Festplatten tauschen, einen Monitor einstellen, Statistiken anzeigen lassen und nat\(:urlich auch die Konfigurationsdatei von
\fBmdadm\fR
bearbeiten\&. Lesen sie vorher das Software\-RAID\-HOWTO\&.
.sp
.RS 4
.nf
http://www\&.linuxhaven\&.de/dlhp/HOWTO/DE\-Software\-RAID\-HOWTO\&.html
.fi
.RE
.SH "OPTIONEN"
.PP
\fBkwraid\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI/etc/mdadm/mdadm\&.conf\fR
.RS 4
Konfigurations Datei f\(:ur
\fBmdadm\fR
(\fBDebian\fR)\&. Siehe
\fBmdadm.conf\fR(5)
f\(:ur weitere Details\&.
.RE
.PP
\fI/etc/mdadm\&.conf\fR
.RS 4
Konfigurations Datei f\(:ur
\fBmdadm\fR
(\fB(Open)SuSE, Fedora und CentOS\fR)\&. Siehe
\fBmdadm.conf\fR(5)
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBmd\fR(4),
\fBmdadm.conf\fR(5),
\fBmdadm\fR(8),
\fBmdmon\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2015 Kai Wilke
.br
