.\"     Title: KWRSYNC_BACKUP
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 11/14/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwrsync_backup
.\"    Source: Version 1.0.3
.\"  Language: English
.\"
.TH "KWRSYNC_BACKUP" "8" "11/14/2013" "Version 1.0.3" "Benutzerhandbuch f\(:ur kwrsync_b"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwrsync_backup \- ein Zshell Script um eine Momentaufnahme von Rechnern zu erstellen\&.
.SH "SYNTAX"
.HP \w'\fBkwrsync_backup\fR\ 'u
\fBkwrsync_backup\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwrsync_backup\fR
k\(:onnen Sie eine Momentaufnahme (Snapshot) von Rechnern machen, auch remote\&. Dies k\(:onnen Sie entweder manuell oder per
\fIcrontab\fR
Eintrag machen\&. Dabei werden die konfigurierten Verzeichnisse gesichert und danach Hardlinks (Rotierung) auf die Dateien/Verzeichnisse erstellt\&.
.SH "OPTIONEN"
.PP
\fBkwrsync_backup\fR hat keine Kommandozeilen Optionen.
.SH "DATEIEN"
.PP
\fI/etc/kwtools/kwrsync_backup\&.cf\fR
.RS 4
Haupt Konfiguration Datei f\(:ur
\fBkwrsync_backup\fR\&. Siehe
\fBkwrsync_backup.cf\fR(5)
f\(:ur weitere Details\&.
.RE
.PP
\fI/etc/kwtools/kwrsync_backup\&.d\fR
.RS 4
Verzeichnis mit den Rechnereigenen Konfigurationsdateien (\fIrechner\&.conf\fR,
\fIrechner\-exclude\&.conf\fR,
\fIrechner\-include\&.conf\fR)
.RE
.SH "SIEHE AUCH"
.PP
\fBkwrsync_backup.cf\fR(5),
\fBkwrsync_backup_cron\fR(8),
\fBrsync\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2002-2013 Kai Wilke
.br
